version: "3.4"
services:
  d113a2e016e12f0f:
    image: oysterpack/appdemo:0.1
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - appdemo-net
    command: -log-level DEBUG -app-id 0xd8e06a3d73a1d426 -release-id 2 -tags A,B,C -app-rpc-port 44228
    ports:
      - 44228:44228
networks:
  appdemo-net: