// Code generated by capnpc-go. DO NOT EDIT.

package capnprpc

import (
	context "golang.org/x/net/context"
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
	server "zombiezen.com/go/capnproto2/server"
)

type App struct{ Client capnp.Client }

// App_TypeID is the unique identifier for the type App.
const App_TypeID = 0xf052e7e084b31199

func (c App) Id(ctx context.Context, params func(App_id_Params) error, opts ...capnp.CallOption) App_id_Results_Promise {
	if c.Client == nil {
		return App_id_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      0,
			InterfaceName: "app.capnp:App",
			MethodName:    "id",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_id_Params{Struct: s}) }
	}
	return App_id_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) ReleaseId(ctx context.Context, params func(App_releaseId_Params) error, opts ...capnp.CallOption) App_releaseId_Results_Promise {
	if c.Client == nil {
		return App_releaseId_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      1,
			InterfaceName: "app.capnp:App",
			MethodName:    "releaseId",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_releaseId_Params{Struct: s}) }
	}
	return App_releaseId_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) Instance(ctx context.Context, params func(App_instance_Params) error, opts ...capnp.CallOption) App_instance_Results_Promise {
	if c.Client == nil {
		return App_instance_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      2,
			InterfaceName: "app.capnp:App",
			MethodName:    "instance",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_instance_Params{Struct: s}) }
	}
	return App_instance_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) StartedOn(ctx context.Context, params func(App_startedOn_Params) error, opts ...capnp.CallOption) App_startedOn_Results_Promise {
	if c.Client == nil {
		return App_startedOn_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      3,
			InterfaceName: "app.capnp:App",
			MethodName:    "startedOn",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_startedOn_Params{Struct: s}) }
	}
	return App_startedOn_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) LogLevel(ctx context.Context, params func(App_logLevel_Params) error, opts ...capnp.CallOption) App_logLevel_Results_Promise {
	if c.Client == nil {
		return App_logLevel_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      4,
			InterfaceName: "app.capnp:App",
			MethodName:    "logLevel",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_logLevel_Params{Struct: s}) }
	}
	return App_logLevel_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) RegisteredServices(ctx context.Context, params func(App_registeredServices_Params) error, opts ...capnp.CallOption) App_registeredServices_Results_Promise {
	if c.Client == nil {
		return App_registeredServices_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      5,
			InterfaceName: "app.capnp:App",
			MethodName:    "registeredServices",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_registeredServices_Params{Struct: s}) }
	}
	return App_registeredServices_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) Service(ctx context.Context, params func(App_service_Params) error, opts ...capnp.CallOption) App_service_Results_Promise {
	if c.Client == nil {
		return App_service_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      6,
			InterfaceName: "app.capnp:App",
			MethodName:    "service",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_service_Params{Struct: s}) }
	}
	return App_service_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) Kill(ctx context.Context, params func(App_kill_Params) error, opts ...capnp.CallOption) App_kill_Results_Promise {
	if c.Client == nil {
		return App_kill_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      7,
			InterfaceName: "app.capnp:App",
			MethodName:    "kill",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_kill_Params{Struct: s}) }
	}
	return App_kill_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}

type App_Server interface {
	Id(App_id) error

	ReleaseId(App_releaseId) error

	Instance(App_instance) error

	StartedOn(App_startedOn) error

	LogLevel(App_logLevel) error

	RegisteredServices(App_registeredServices) error

	Service(App_service) error

	Kill(App_kill) error
}

func App_ServerToClient(s App_Server) App {
	c, _ := s.(server.Closer)
	return App{Client: server.New(App_Methods(nil, s), c)}
}

func App_Methods(methods []server.Method, s App_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 8)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      0,
			InterfaceName: "app.capnp:App",
			MethodName:    "id",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_id{c, opts, App_id_Params{Struct: p}, App_id_Results{Struct: r}}
			return s.Id(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      1,
			InterfaceName: "app.capnp:App",
			MethodName:    "releaseId",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_releaseId{c, opts, App_releaseId_Params{Struct: p}, App_releaseId_Results{Struct: r}}
			return s.ReleaseId(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      2,
			InterfaceName: "app.capnp:App",
			MethodName:    "instance",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_instance{c, opts, App_instance_Params{Struct: p}, App_instance_Results{Struct: r}}
			return s.Instance(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      3,
			InterfaceName: "app.capnp:App",
			MethodName:    "startedOn",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_startedOn{c, opts, App_startedOn_Params{Struct: p}, App_startedOn_Results{Struct: r}}
			return s.StartedOn(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      4,
			InterfaceName: "app.capnp:App",
			MethodName:    "logLevel",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_logLevel{c, opts, App_logLevel_Params{Struct: p}, App_logLevel_Results{Struct: r}}
			return s.LogLevel(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      5,
			InterfaceName: "app.capnp:App",
			MethodName:    "registeredServices",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_registeredServices{c, opts, App_registeredServices_Params{Struct: p}, App_registeredServices_Results{Struct: r}}
			return s.RegisteredServices(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      6,
			InterfaceName: "app.capnp:App",
			MethodName:    "service",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_service{c, opts, App_service_Params{Struct: p}, App_service_Results{Struct: r}}
			return s.Service(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      7,
			InterfaceName: "app.capnp:App",
			MethodName:    "kill",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_kill{c, opts, App_kill_Params{Struct: p}, App_kill_Results{Struct: r}}
			return s.Kill(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 0},
	})

	return methods
}

// App_id holds the arguments for a server call to App.id.
type App_id struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_id_Params
	Results App_id_Results
}

// App_releaseId holds the arguments for a server call to App.releaseId.
type App_releaseId struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_releaseId_Params
	Results App_releaseId_Results
}

// App_instance holds the arguments for a server call to App.instance.
type App_instance struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_instance_Params
	Results App_instance_Results
}

// App_startedOn holds the arguments for a server call to App.startedOn.
type App_startedOn struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_startedOn_Params
	Results App_startedOn_Results
}

// App_logLevel holds the arguments for a server call to App.logLevel.
type App_logLevel struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_logLevel_Params
	Results App_logLevel_Results
}

// App_registeredServices holds the arguments for a server call to App.registeredServices.
type App_registeredServices struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_registeredServices_Params
	Results App_registeredServices_Results
}

// App_service holds the arguments for a server call to App.service.
type App_service struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_service_Params
	Results App_service_Results
}

// App_kill holds the arguments for a server call to App.kill.
type App_kill struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_kill_Params
	Results App_kill_Results
}

type App_id_Params struct{ capnp.Struct }

// App_id_Params_TypeID is the unique identifier for the type App_id_Params.
const App_id_Params_TypeID = 0xa56ff1a4dc4cdcd8

func NewApp_id_Params(s *capnp.Segment) (App_id_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_id_Params{st}, err
}

func NewRootApp_id_Params(s *capnp.Segment) (App_id_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_id_Params{st}, err
}

func ReadRootApp_id_Params(msg *capnp.Message) (App_id_Params, error) {
	root, err := msg.RootPtr()
	return App_id_Params{root.Struct()}, err
}

func (s App_id_Params) String() string {
	str, _ := text.Marshal(0xa56ff1a4dc4cdcd8, s.Struct)
	return str
}

// App_id_Params_List is a list of App_id_Params.
type App_id_Params_List struct{ capnp.List }

// NewApp_id_Params creates a new list of App_id_Params.
func NewApp_id_Params_List(s *capnp.Segment, sz int32) (App_id_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_id_Params_List{l}, err
}

func (s App_id_Params_List) At(i int) App_id_Params { return App_id_Params{s.List.Struct(i)} }

func (s App_id_Params_List) Set(i int, v App_id_Params) error { return s.List.SetStruct(i, v.Struct) }

func (s App_id_Params_List) String() string {
	str, _ := text.MarshalList(0xa56ff1a4dc4cdcd8, s.List)
	return str
}

// App_id_Params_Promise is a wrapper for a App_id_Params promised by a client call.
type App_id_Params_Promise struct{ *capnp.Pipeline }

func (p App_id_Params_Promise) Struct() (App_id_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_id_Params{s}, err
}

type App_id_Results struct{ capnp.Struct }

// App_id_Results_TypeID is the unique identifier for the type App_id_Results.
const App_id_Results_TypeID = 0xd2592928fa547bc6

func NewApp_id_Results(s *capnp.Segment) (App_id_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_id_Results{st}, err
}

func NewRootApp_id_Results(s *capnp.Segment) (App_id_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_id_Results{st}, err
}

func ReadRootApp_id_Results(msg *capnp.Message) (App_id_Results, error) {
	root, err := msg.RootPtr()
	return App_id_Results{root.Struct()}, err
}

func (s App_id_Results) String() string {
	str, _ := text.Marshal(0xd2592928fa547bc6, s.Struct)
	return str
}

func (s App_id_Results) AppId() uint64 {
	return s.Struct.Uint64(0)
}

func (s App_id_Results) SetAppId(v uint64) {
	s.Struct.SetUint64(0, v)
}

// App_id_Results_List is a list of App_id_Results.
type App_id_Results_List struct{ capnp.List }

// NewApp_id_Results creates a new list of App_id_Results.
func NewApp_id_Results_List(s *capnp.Segment, sz int32) (App_id_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return App_id_Results_List{l}, err
}

func (s App_id_Results_List) At(i int) App_id_Results { return App_id_Results{s.List.Struct(i)} }

func (s App_id_Results_List) Set(i int, v App_id_Results) error { return s.List.SetStruct(i, v.Struct) }

func (s App_id_Results_List) String() string {
	str, _ := text.MarshalList(0xd2592928fa547bc6, s.List)
	return str
}

// App_id_Results_Promise is a wrapper for a App_id_Results promised by a client call.
type App_id_Results_Promise struct{ *capnp.Pipeline }

func (p App_id_Results_Promise) Struct() (App_id_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_id_Results{s}, err
}

type App_releaseId_Params struct{ capnp.Struct }

// App_releaseId_Params_TypeID is the unique identifier for the type App_releaseId_Params.
const App_releaseId_Params_TypeID = 0xbea6ce314a7abc79

func NewApp_releaseId_Params(s *capnp.Segment) (App_releaseId_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_releaseId_Params{st}, err
}

func NewRootApp_releaseId_Params(s *capnp.Segment) (App_releaseId_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_releaseId_Params{st}, err
}

func ReadRootApp_releaseId_Params(msg *capnp.Message) (App_releaseId_Params, error) {
	root, err := msg.RootPtr()
	return App_releaseId_Params{root.Struct()}, err
}

func (s App_releaseId_Params) String() string {
	str, _ := text.Marshal(0xbea6ce314a7abc79, s.Struct)
	return str
}

// App_releaseId_Params_List is a list of App_releaseId_Params.
type App_releaseId_Params_List struct{ capnp.List }

// NewApp_releaseId_Params creates a new list of App_releaseId_Params.
func NewApp_releaseId_Params_List(s *capnp.Segment, sz int32) (App_releaseId_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_releaseId_Params_List{l}, err
}

func (s App_releaseId_Params_List) At(i int) App_releaseId_Params {
	return App_releaseId_Params{s.List.Struct(i)}
}

func (s App_releaseId_Params_List) Set(i int, v App_releaseId_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_releaseId_Params_List) String() string {
	str, _ := text.MarshalList(0xbea6ce314a7abc79, s.List)
	return str
}

// App_releaseId_Params_Promise is a wrapper for a App_releaseId_Params promised by a client call.
type App_releaseId_Params_Promise struct{ *capnp.Pipeline }

func (p App_releaseId_Params_Promise) Struct() (App_releaseId_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_releaseId_Params{s}, err
}

type App_releaseId_Results struct{ capnp.Struct }

// App_releaseId_Results_TypeID is the unique identifier for the type App_releaseId_Results.
const App_releaseId_Results_TypeID = 0x92a4f36c8d41b673

func NewApp_releaseId_Results(s *capnp.Segment) (App_releaseId_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_releaseId_Results{st}, err
}

func NewRootApp_releaseId_Results(s *capnp.Segment) (App_releaseId_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_releaseId_Results{st}, err
}

func ReadRootApp_releaseId_Results(msg *capnp.Message) (App_releaseId_Results, error) {
	root, err := msg.RootPtr()
	return App_releaseId_Results{root.Struct()}, err
}

func (s App_releaseId_Results) String() string {
	str, _ := text.Marshal(0x92a4f36c8d41b673, s.Struct)
	return str
}

func (s App_releaseId_Results) ReleaseId() uint64 {
	return s.Struct.Uint64(0)
}

func (s App_releaseId_Results) SetReleaseId(v uint64) {
	s.Struct.SetUint64(0, v)
}

// App_releaseId_Results_List is a list of App_releaseId_Results.
type App_releaseId_Results_List struct{ capnp.List }

// NewApp_releaseId_Results creates a new list of App_releaseId_Results.
func NewApp_releaseId_Results_List(s *capnp.Segment, sz int32) (App_releaseId_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return App_releaseId_Results_List{l}, err
}

func (s App_releaseId_Results_List) At(i int) App_releaseId_Results {
	return App_releaseId_Results{s.List.Struct(i)}
}

func (s App_releaseId_Results_List) Set(i int, v App_releaseId_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_releaseId_Results_List) String() string {
	str, _ := text.MarshalList(0x92a4f36c8d41b673, s.List)
	return str
}

// App_releaseId_Results_Promise is a wrapper for a App_releaseId_Results promised by a client call.
type App_releaseId_Results_Promise struct{ *capnp.Pipeline }

func (p App_releaseId_Results_Promise) Struct() (App_releaseId_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_releaseId_Results{s}, err
}

type App_instance_Params struct{ capnp.Struct }

// App_instance_Params_TypeID is the unique identifier for the type App_instance_Params.
const App_instance_Params_TypeID = 0x84e4b51ba5570071

func NewApp_instance_Params(s *capnp.Segment) (App_instance_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_instance_Params{st}, err
}

func NewRootApp_instance_Params(s *capnp.Segment) (App_instance_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_instance_Params{st}, err
}

func ReadRootApp_instance_Params(msg *capnp.Message) (App_instance_Params, error) {
	root, err := msg.RootPtr()
	return App_instance_Params{root.Struct()}, err
}

func (s App_instance_Params) String() string {
	str, _ := text.Marshal(0x84e4b51ba5570071, s.Struct)
	return str
}

// App_instance_Params_List is a list of App_instance_Params.
type App_instance_Params_List struct{ capnp.List }

// NewApp_instance_Params creates a new list of App_instance_Params.
func NewApp_instance_Params_List(s *capnp.Segment, sz int32) (App_instance_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_instance_Params_List{l}, err
}

func (s App_instance_Params_List) At(i int) App_instance_Params {
	return App_instance_Params{s.List.Struct(i)}
}

func (s App_instance_Params_List) Set(i int, v App_instance_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_instance_Params_List) String() string {
	str, _ := text.MarshalList(0x84e4b51ba5570071, s.List)
	return str
}

// App_instance_Params_Promise is a wrapper for a App_instance_Params promised by a client call.
type App_instance_Params_Promise struct{ *capnp.Pipeline }

func (p App_instance_Params_Promise) Struct() (App_instance_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_instance_Params{s}, err
}

type App_instance_Results struct{ capnp.Struct }

// App_instance_Results_TypeID is the unique identifier for the type App_instance_Results.
const App_instance_Results_TypeID = 0xb5031b975a2f2d5d

func NewApp_instance_Results(s *capnp.Segment) (App_instance_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_instance_Results{st}, err
}

func NewRootApp_instance_Results(s *capnp.Segment) (App_instance_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_instance_Results{st}, err
}

func ReadRootApp_instance_Results(msg *capnp.Message) (App_instance_Results, error) {
	root, err := msg.RootPtr()
	return App_instance_Results{root.Struct()}, err
}

func (s App_instance_Results) String() string {
	str, _ := text.Marshal(0xb5031b975a2f2d5d, s.Struct)
	return str
}

func (s App_instance_Results) InstanceId() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s App_instance_Results) HasInstanceId() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s App_instance_Results) InstanceIdBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s App_instance_Results) SetInstanceId(v string) error {
	return s.Struct.SetText(0, v)
}

// App_instance_Results_List is a list of App_instance_Results.
type App_instance_Results_List struct{ capnp.List }

// NewApp_instance_Results creates a new list of App_instance_Results.
func NewApp_instance_Results_List(s *capnp.Segment, sz int32) (App_instance_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return App_instance_Results_List{l}, err
}

func (s App_instance_Results_List) At(i int) App_instance_Results {
	return App_instance_Results{s.List.Struct(i)}
}

func (s App_instance_Results_List) Set(i int, v App_instance_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_instance_Results_List) String() string {
	str, _ := text.MarshalList(0xb5031b975a2f2d5d, s.List)
	return str
}

// App_instance_Results_Promise is a wrapper for a App_instance_Results promised by a client call.
type App_instance_Results_Promise struct{ *capnp.Pipeline }

func (p App_instance_Results_Promise) Struct() (App_instance_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_instance_Results{s}, err
}

type App_startedOn_Params struct{ capnp.Struct }

// App_startedOn_Params_TypeID is the unique identifier for the type App_startedOn_Params.
const App_startedOn_Params_TypeID = 0x8ff15814cd06ecd7

func NewApp_startedOn_Params(s *capnp.Segment) (App_startedOn_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_startedOn_Params{st}, err
}

func NewRootApp_startedOn_Params(s *capnp.Segment) (App_startedOn_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_startedOn_Params{st}, err
}

func ReadRootApp_startedOn_Params(msg *capnp.Message) (App_startedOn_Params, error) {
	root, err := msg.RootPtr()
	return App_startedOn_Params{root.Struct()}, err
}

func (s App_startedOn_Params) String() string {
	str, _ := text.Marshal(0x8ff15814cd06ecd7, s.Struct)
	return str
}

// App_startedOn_Params_List is a list of App_startedOn_Params.
type App_startedOn_Params_List struct{ capnp.List }

// NewApp_startedOn_Params creates a new list of App_startedOn_Params.
func NewApp_startedOn_Params_List(s *capnp.Segment, sz int32) (App_startedOn_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_startedOn_Params_List{l}, err
}

func (s App_startedOn_Params_List) At(i int) App_startedOn_Params {
	return App_startedOn_Params{s.List.Struct(i)}
}

func (s App_startedOn_Params_List) Set(i int, v App_startedOn_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_startedOn_Params_List) String() string {
	str, _ := text.MarshalList(0x8ff15814cd06ecd7, s.List)
	return str
}

// App_startedOn_Params_Promise is a wrapper for a App_startedOn_Params promised by a client call.
type App_startedOn_Params_Promise struct{ *capnp.Pipeline }

func (p App_startedOn_Params_Promise) Struct() (App_startedOn_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_startedOn_Params{s}, err
}

type App_startedOn_Results struct{ capnp.Struct }

// App_startedOn_Results_TypeID is the unique identifier for the type App_startedOn_Results.
const App_startedOn_Results_TypeID = 0x8ff88405c5bd0dec

func NewApp_startedOn_Results(s *capnp.Segment) (App_startedOn_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_startedOn_Results{st}, err
}

func NewRootApp_startedOn_Results(s *capnp.Segment) (App_startedOn_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_startedOn_Results{st}, err
}

func ReadRootApp_startedOn_Results(msg *capnp.Message) (App_startedOn_Results, error) {
	root, err := msg.RootPtr()
	return App_startedOn_Results{root.Struct()}, err
}

func (s App_startedOn_Results) String() string {
	str, _ := text.Marshal(0x8ff88405c5bd0dec, s.Struct)
	return str
}

func (s App_startedOn_Results) StartedOn() int64 {
	return int64(s.Struct.Uint64(0))
}

func (s App_startedOn_Results) SetStartedOn(v int64) {
	s.Struct.SetUint64(0, uint64(v))
}

// App_startedOn_Results_List is a list of App_startedOn_Results.
type App_startedOn_Results_List struct{ capnp.List }

// NewApp_startedOn_Results creates a new list of App_startedOn_Results.
func NewApp_startedOn_Results_List(s *capnp.Segment, sz int32) (App_startedOn_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return App_startedOn_Results_List{l}, err
}

func (s App_startedOn_Results_List) At(i int) App_startedOn_Results {
	return App_startedOn_Results{s.List.Struct(i)}
}

func (s App_startedOn_Results_List) Set(i int, v App_startedOn_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_startedOn_Results_List) String() string {
	str, _ := text.MarshalList(0x8ff88405c5bd0dec, s.List)
	return str
}

// App_startedOn_Results_Promise is a wrapper for a App_startedOn_Results promised by a client call.
type App_startedOn_Results_Promise struct{ *capnp.Pipeline }

func (p App_startedOn_Results_Promise) Struct() (App_startedOn_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_startedOn_Results{s}, err
}

type App_logLevel_Params struct{ capnp.Struct }

// App_logLevel_Params_TypeID is the unique identifier for the type App_logLevel_Params.
const App_logLevel_Params_TypeID = 0xa9121e4800ff7069

func NewApp_logLevel_Params(s *capnp.Segment) (App_logLevel_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_logLevel_Params{st}, err
}

func NewRootApp_logLevel_Params(s *capnp.Segment) (App_logLevel_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_logLevel_Params{st}, err
}

func ReadRootApp_logLevel_Params(msg *capnp.Message) (App_logLevel_Params, error) {
	root, err := msg.RootPtr()
	return App_logLevel_Params{root.Struct()}, err
}

func (s App_logLevel_Params) String() string {
	str, _ := text.Marshal(0xa9121e4800ff7069, s.Struct)
	return str
}

// App_logLevel_Params_List is a list of App_logLevel_Params.
type App_logLevel_Params_List struct{ capnp.List }

// NewApp_logLevel_Params creates a new list of App_logLevel_Params.
func NewApp_logLevel_Params_List(s *capnp.Segment, sz int32) (App_logLevel_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_logLevel_Params_List{l}, err
}

func (s App_logLevel_Params_List) At(i int) App_logLevel_Params {
	return App_logLevel_Params{s.List.Struct(i)}
}

func (s App_logLevel_Params_List) Set(i int, v App_logLevel_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_logLevel_Params_List) String() string {
	str, _ := text.MarshalList(0xa9121e4800ff7069, s.List)
	return str
}

// App_logLevel_Params_Promise is a wrapper for a App_logLevel_Params promised by a client call.
type App_logLevel_Params_Promise struct{ *capnp.Pipeline }

func (p App_logLevel_Params_Promise) Struct() (App_logLevel_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_logLevel_Params{s}, err
}

type App_logLevel_Results struct{ capnp.Struct }

// App_logLevel_Results_TypeID is the unique identifier for the type App_logLevel_Results.
const App_logLevel_Results_TypeID = 0xae6825c3fecb35bf

func NewApp_logLevel_Results(s *capnp.Segment) (App_logLevel_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_logLevel_Results{st}, err
}

func NewRootApp_logLevel_Results(s *capnp.Segment) (App_logLevel_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_logLevel_Results{st}, err
}

func ReadRootApp_logLevel_Results(msg *capnp.Message) (App_logLevel_Results, error) {
	root, err := msg.RootPtr()
	return App_logLevel_Results{root.Struct()}, err
}

func (s App_logLevel_Results) String() string {
	str, _ := text.Marshal(0xae6825c3fecb35bf, s.Struct)
	return str
}

func (s App_logLevel_Results) Level() LogLevel {
	return LogLevel(s.Struct.Uint16(0))
}

func (s App_logLevel_Results) SetLevel(v LogLevel) {
	s.Struct.SetUint16(0, uint16(v))
}

// App_logLevel_Results_List is a list of App_logLevel_Results.
type App_logLevel_Results_List struct{ capnp.List }

// NewApp_logLevel_Results creates a new list of App_logLevel_Results.
func NewApp_logLevel_Results_List(s *capnp.Segment, sz int32) (App_logLevel_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return App_logLevel_Results_List{l}, err
}

func (s App_logLevel_Results_List) At(i int) App_logLevel_Results {
	return App_logLevel_Results{s.List.Struct(i)}
}

func (s App_logLevel_Results_List) Set(i int, v App_logLevel_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_logLevel_Results_List) String() string {
	str, _ := text.MarshalList(0xae6825c3fecb35bf, s.List)
	return str
}

// App_logLevel_Results_Promise is a wrapper for a App_logLevel_Results promised by a client call.
type App_logLevel_Results_Promise struct{ *capnp.Pipeline }

func (p App_logLevel_Results_Promise) Struct() (App_logLevel_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_logLevel_Results{s}, err
}

type App_registeredServices_Params struct{ capnp.Struct }

// App_registeredServices_Params_TypeID is the unique identifier for the type App_registeredServices_Params.
const App_registeredServices_Params_TypeID = 0xb95426b082b00c25

func NewApp_registeredServices_Params(s *capnp.Segment) (App_registeredServices_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_registeredServices_Params{st}, err
}

func NewRootApp_registeredServices_Params(s *capnp.Segment) (App_registeredServices_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_registeredServices_Params{st}, err
}

func ReadRootApp_registeredServices_Params(msg *capnp.Message) (App_registeredServices_Params, error) {
	root, err := msg.RootPtr()
	return App_registeredServices_Params{root.Struct()}, err
}

func (s App_registeredServices_Params) String() string {
	str, _ := text.Marshal(0xb95426b082b00c25, s.Struct)
	return str
}

// App_registeredServices_Params_List is a list of App_registeredServices_Params.
type App_registeredServices_Params_List struct{ capnp.List }

// NewApp_registeredServices_Params creates a new list of App_registeredServices_Params.
func NewApp_registeredServices_Params_List(s *capnp.Segment, sz int32) (App_registeredServices_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_registeredServices_Params_List{l}, err
}

func (s App_registeredServices_Params_List) At(i int) App_registeredServices_Params {
	return App_registeredServices_Params{s.List.Struct(i)}
}

func (s App_registeredServices_Params_List) Set(i int, v App_registeredServices_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_registeredServices_Params_List) String() string {
	str, _ := text.MarshalList(0xb95426b082b00c25, s.List)
	return str
}

// App_registeredServices_Params_Promise is a wrapper for a App_registeredServices_Params promised by a client call.
type App_registeredServices_Params_Promise struct{ *capnp.Pipeline }

func (p App_registeredServices_Params_Promise) Struct() (App_registeredServices_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_registeredServices_Params{s}, err
}

type App_registeredServices_Results struct{ capnp.Struct }

// App_registeredServices_Results_TypeID is the unique identifier for the type App_registeredServices_Results.
const App_registeredServices_Results_TypeID = 0xeb68797cd74f95c2

func NewApp_registeredServices_Results(s *capnp.Segment) (App_registeredServices_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_registeredServices_Results{st}, err
}

func NewRootApp_registeredServices_Results(s *capnp.Segment) (App_registeredServices_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_registeredServices_Results{st}, err
}

func ReadRootApp_registeredServices_Results(msg *capnp.Message) (App_registeredServices_Results, error) {
	root, err := msg.RootPtr()
	return App_registeredServices_Results{root.Struct()}, err
}

func (s App_registeredServices_Results) String() string {
	str, _ := text.Marshal(0xeb68797cd74f95c2, s.Struct)
	return str
}

func (s App_registeredServices_Results) ServiceIds() (capnp.UInt64List, error) {
	p, err := s.Struct.Ptr(0)
	return capnp.UInt64List{List: p.List()}, err
}

func (s App_registeredServices_Results) HasServiceIds() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s App_registeredServices_Results) SetServiceIds(v capnp.UInt64List) error {
	return s.Struct.SetPtr(0, v.List.ToPtr())
}

// NewServiceIds sets the serviceIds field to a newly
// allocated capnp.UInt64List, preferring placement in s's segment.
func (s App_registeredServices_Results) NewServiceIds(n int32) (capnp.UInt64List, error) {
	l, err := capnp.NewUInt64List(s.Struct.Segment(), n)
	if err != nil {
		return capnp.UInt64List{}, err
	}
	err = s.Struct.SetPtr(0, l.List.ToPtr())
	return l, err
}

// App_registeredServices_Results_List is a list of App_registeredServices_Results.
type App_registeredServices_Results_List struct{ capnp.List }

// NewApp_registeredServices_Results creates a new list of App_registeredServices_Results.
func NewApp_registeredServices_Results_List(s *capnp.Segment, sz int32) (App_registeredServices_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return App_registeredServices_Results_List{l}, err
}

func (s App_registeredServices_Results_List) At(i int) App_registeredServices_Results {
	return App_registeredServices_Results{s.List.Struct(i)}
}

func (s App_registeredServices_Results_List) Set(i int, v App_registeredServices_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_registeredServices_Results_List) String() string {
	str, _ := text.MarshalList(0xeb68797cd74f95c2, s.List)
	return str
}

// App_registeredServices_Results_Promise is a wrapper for a App_registeredServices_Results promised by a client call.
type App_registeredServices_Results_Promise struct{ *capnp.Pipeline }

func (p App_registeredServices_Results_Promise) Struct() (App_registeredServices_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_registeredServices_Results{s}, err
}

type App_service_Params struct{ capnp.Struct }

// App_service_Params_TypeID is the unique identifier for the type App_service_Params.
const App_service_Params_TypeID = 0xa504000ac6204c12

func NewApp_service_Params(s *capnp.Segment) (App_service_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_service_Params{st}, err
}

func NewRootApp_service_Params(s *capnp.Segment) (App_service_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_service_Params{st}, err
}

func ReadRootApp_service_Params(msg *capnp.Message) (App_service_Params, error) {
	root, err := msg.RootPtr()
	return App_service_Params{root.Struct()}, err
}

func (s App_service_Params) String() string {
	str, _ := text.Marshal(0xa504000ac6204c12, s.Struct)
	return str
}

func (s App_service_Params) Id() uint64 {
	return s.Struct.Uint64(0)
}

func (s App_service_Params) SetId(v uint64) {
	s.Struct.SetUint64(0, v)
}

// App_service_Params_List is a list of App_service_Params.
type App_service_Params_List struct{ capnp.List }

// NewApp_service_Params creates a new list of App_service_Params.
func NewApp_service_Params_List(s *capnp.Segment, sz int32) (App_service_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return App_service_Params_List{l}, err
}

func (s App_service_Params_List) At(i int) App_service_Params {
	return App_service_Params{s.List.Struct(i)}
}

func (s App_service_Params_List) Set(i int, v App_service_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_service_Params_List) String() string {
	str, _ := text.MarshalList(0xa504000ac6204c12, s.List)
	return str
}

// App_service_Params_Promise is a wrapper for a App_service_Params promised by a client call.
type App_service_Params_Promise struct{ *capnp.Pipeline }

func (p App_service_Params_Promise) Struct() (App_service_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_service_Params{s}, err
}

type App_service_Results struct{ capnp.Struct }

// App_service_Results_TypeID is the unique identifier for the type App_service_Results.
const App_service_Results_TypeID = 0xfa41cf108b6d790d

func NewApp_service_Results(s *capnp.Segment) (App_service_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_service_Results{st}, err
}

func NewRootApp_service_Results(s *capnp.Segment) (App_service_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_service_Results{st}, err
}

func ReadRootApp_service_Results(msg *capnp.Message) (App_service_Results, error) {
	root, err := msg.RootPtr()
	return App_service_Results{root.Struct()}, err
}

func (s App_service_Results) String() string {
	str, _ := text.Marshal(0xfa41cf108b6d790d, s.Struct)
	return str
}

func (s App_service_Results) Service() Service {
	p, _ := s.Struct.Ptr(0)
	return Service{Client: p.Interface().Client()}
}

func (s App_service_Results) HasService() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s App_service_Results) SetService(v Service) error {
	if v.Client == nil {
		return s.Struct.SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(v.Client))
	return s.Struct.SetPtr(0, in.ToPtr())
}

// App_service_Results_List is a list of App_service_Results.
type App_service_Results_List struct{ capnp.List }

// NewApp_service_Results creates a new list of App_service_Results.
func NewApp_service_Results_List(s *capnp.Segment, sz int32) (App_service_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return App_service_Results_List{l}, err
}

func (s App_service_Results_List) At(i int) App_service_Results {
	return App_service_Results{s.List.Struct(i)}
}

func (s App_service_Results_List) Set(i int, v App_service_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_service_Results_List) String() string {
	str, _ := text.MarshalList(0xfa41cf108b6d790d, s.List)
	return str
}

// App_service_Results_Promise is a wrapper for a App_service_Results promised by a client call.
type App_service_Results_Promise struct{ *capnp.Pipeline }

func (p App_service_Results_Promise) Struct() (App_service_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_service_Results{s}, err
}

func (p App_service_Results_Promise) Service() Service {
	return Service{Client: p.Pipeline.GetPipeline(0).Client()}
}

type App_kill_Params struct{ capnp.Struct }

// App_kill_Params_TypeID is the unique identifier for the type App_kill_Params.
const App_kill_Params_TypeID = 0xd47381c89e2f1649

func NewApp_kill_Params(s *capnp.Segment) (App_kill_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_kill_Params{st}, err
}

func NewRootApp_kill_Params(s *capnp.Segment) (App_kill_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_kill_Params{st}, err
}

func ReadRootApp_kill_Params(msg *capnp.Message) (App_kill_Params, error) {
	root, err := msg.RootPtr()
	return App_kill_Params{root.Struct()}, err
}

func (s App_kill_Params) String() string {
	str, _ := text.Marshal(0xd47381c89e2f1649, s.Struct)
	return str
}

// App_kill_Params_List is a list of App_kill_Params.
type App_kill_Params_List struct{ capnp.List }

// NewApp_kill_Params creates a new list of App_kill_Params.
func NewApp_kill_Params_List(s *capnp.Segment, sz int32) (App_kill_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_kill_Params_List{l}, err
}

func (s App_kill_Params_List) At(i int) App_kill_Params { return App_kill_Params{s.List.Struct(i)} }

func (s App_kill_Params_List) Set(i int, v App_kill_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_kill_Params_List) String() string {
	str, _ := text.MarshalList(0xd47381c89e2f1649, s.List)
	return str
}

// App_kill_Params_Promise is a wrapper for a App_kill_Params promised by a client call.
type App_kill_Params_Promise struct{ *capnp.Pipeline }

func (p App_kill_Params_Promise) Struct() (App_kill_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_kill_Params{s}, err
}

type App_kill_Results struct{ capnp.Struct }

// App_kill_Results_TypeID is the unique identifier for the type App_kill_Results.
const App_kill_Results_TypeID = 0xac531ffcc2cdbf05

func NewApp_kill_Results(s *capnp.Segment) (App_kill_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_kill_Results{st}, err
}

func NewRootApp_kill_Results(s *capnp.Segment) (App_kill_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_kill_Results{st}, err
}

func ReadRootApp_kill_Results(msg *capnp.Message) (App_kill_Results, error) {
	root, err := msg.RootPtr()
	return App_kill_Results{root.Struct()}, err
}

func (s App_kill_Results) String() string {
	str, _ := text.Marshal(0xac531ffcc2cdbf05, s.Struct)
	return str
}

// App_kill_Results_List is a list of App_kill_Results.
type App_kill_Results_List struct{ capnp.List }

// NewApp_kill_Results creates a new list of App_kill_Results.
func NewApp_kill_Results_List(s *capnp.Segment, sz int32) (App_kill_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_kill_Results_List{l}, err
}

func (s App_kill_Results_List) At(i int) App_kill_Results { return App_kill_Results{s.List.Struct(i)} }

func (s App_kill_Results_List) Set(i int, v App_kill_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_kill_Results_List) String() string {
	str, _ := text.MarshalList(0xac531ffcc2cdbf05, s.List)
	return str
}

// App_kill_Results_Promise is a wrapper for a App_kill_Results promised by a client call.
type App_kill_Results_Promise struct{ *capnp.Pipeline }

func (p App_kill_Results_Promise) Struct() (App_kill_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_kill_Results{s}, err
}

type LogLevel uint16

// LogLevel_TypeID is the unique identifier for the type LogLevel.
const LogLevel_TypeID = 0xce802aa8977a9aee

// Values of LogLevel.
const (
	LogLevel_debug LogLevel = 0
	LogLevel_info  LogLevel = 1
	LogLevel_warn  LogLevel = 2
	LogLevel_error LogLevel = 3
)

// String returns the enum's constant name.
func (c LogLevel) String() string {
	switch c {
	case LogLevel_debug:
		return "debug"
	case LogLevel_info:
		return "info"
	case LogLevel_warn:
		return "warn"
	case LogLevel_error:
		return "error"

	default:
		return ""
	}
}

// LogLevelFromString returns the enum value with a name,
// or the zero value if there's no such value.
func LogLevelFromString(c string) LogLevel {
	switch c {
	case "debug":
		return LogLevel_debug
	case "info":
		return LogLevel_info
	case "warn":
		return LogLevel_warn
	case "error":
		return LogLevel_error

	default:
		return 0
	}
}

type LogLevel_List struct{ capnp.List }

func NewLogLevel_List(s *capnp.Segment, sz int32) (LogLevel_List, error) {
	l, err := capnp.NewUInt16List(s, sz)
	return LogLevel_List{l.List}, err
}

func (l LogLevel_List) At(i int) LogLevel {
	ul := capnp.UInt16List{List: l.List}
	return LogLevel(ul.At(i))
}

func (l LogLevel_List) Set(i int, v LogLevel) {
	ul := capnp.UInt16List{List: l.List}
	ul.Set(i, uint16(v))
}

type Service struct{ Client capnp.Client }

// Service_TypeID is the unique identifier for the type Service.
const Service_TypeID = 0xb25b411cec149334

func (c Service) Id(ctx context.Context, params func(Service_id_Params) error, opts ...capnp.CallOption) Service_id_Results_Promise {
	if c.Client == nil {
		return Service_id_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      0,
			InterfaceName: "app.capnp:Service",
			MethodName:    "id",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(Service_id_Params{Struct: s}) }
	}
	return Service_id_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c Service) LogLevel(ctx context.Context, params func(Service_logLevel_Params) error, opts ...capnp.CallOption) Service_logLevel_Results_Promise {
	if c.Client == nil {
		return Service_logLevel_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      1,
			InterfaceName: "app.capnp:Service",
			MethodName:    "logLevel",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(Service_logLevel_Params{Struct: s}) }
	}
	return Service_logLevel_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c Service) Alive(ctx context.Context, params func(Service_alive_Params) error, opts ...capnp.CallOption) Service_alive_Results_Promise {
	if c.Client == nil {
		return Service_alive_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      2,
			InterfaceName: "app.capnp:Service",
			MethodName:    "alive",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(Service_alive_Params{Struct: s}) }
	}
	return Service_alive_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c Service) Kill(ctx context.Context, params func(Service_kill_Params) error, opts ...capnp.CallOption) Service_kill_Results_Promise {
	if c.Client == nil {
		return Service_kill_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      3,
			InterfaceName: "app.capnp:Service",
			MethodName:    "kill",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(Service_kill_Params{Struct: s}) }
	}
	return Service_kill_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}

type Service_Server interface {
	Id(Service_id) error

	LogLevel(Service_logLevel) error

	Alive(Service_alive) error

	Kill(Service_kill) error
}

func Service_ServerToClient(s Service_Server) Service {
	c, _ := s.(server.Closer)
	return Service{Client: server.New(Service_Methods(nil, s), c)}
}

func Service_Methods(methods []server.Method, s Service_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      0,
			InterfaceName: "app.capnp:Service",
			MethodName:    "id",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := Service_id{c, opts, Service_id_Params{Struct: p}, Service_id_Results{Struct: r}}
			return s.Id(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      1,
			InterfaceName: "app.capnp:Service",
			MethodName:    "logLevel",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := Service_logLevel{c, opts, Service_logLevel_Params{Struct: p}, Service_logLevel_Results{Struct: r}}
			return s.LogLevel(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      2,
			InterfaceName: "app.capnp:Service",
			MethodName:    "alive",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := Service_alive{c, opts, Service_alive_Params{Struct: p}, Service_alive_Results{Struct: r}}
			return s.Alive(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      3,
			InterfaceName: "app.capnp:Service",
			MethodName:    "kill",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := Service_kill{c, opts, Service_kill_Params{Struct: p}, Service_kill_Results{Struct: r}}
			return s.Kill(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 0},
	})

	return methods
}

// Service_id holds the arguments for a server call to Service.id.
type Service_id struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  Service_id_Params
	Results Service_id_Results
}

// Service_logLevel holds the arguments for a server call to Service.logLevel.
type Service_logLevel struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  Service_logLevel_Params
	Results Service_logLevel_Results
}

// Service_alive holds the arguments for a server call to Service.alive.
type Service_alive struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  Service_alive_Params
	Results Service_alive_Results
}

// Service_kill holds the arguments for a server call to Service.kill.
type Service_kill struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  Service_kill_Params
	Results Service_kill_Results
}

type Service_id_Params struct{ capnp.Struct }

// Service_id_Params_TypeID is the unique identifier for the type Service_id_Params.
const Service_id_Params_TypeID = 0x965465bd75220f94

func NewService_id_Params(s *capnp.Segment) (Service_id_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_id_Params{st}, err
}

func NewRootService_id_Params(s *capnp.Segment) (Service_id_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_id_Params{st}, err
}

func ReadRootService_id_Params(msg *capnp.Message) (Service_id_Params, error) {
	root, err := msg.RootPtr()
	return Service_id_Params{root.Struct()}, err
}

func (s Service_id_Params) String() string {
	str, _ := text.Marshal(0x965465bd75220f94, s.Struct)
	return str
}

// Service_id_Params_List is a list of Service_id_Params.
type Service_id_Params_List struct{ capnp.List }

// NewService_id_Params creates a new list of Service_id_Params.
func NewService_id_Params_List(s *capnp.Segment, sz int32) (Service_id_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Service_id_Params_List{l}, err
}

func (s Service_id_Params_List) At(i int) Service_id_Params {
	return Service_id_Params{s.List.Struct(i)}
}

func (s Service_id_Params_List) Set(i int, v Service_id_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_id_Params_List) String() string {
	str, _ := text.MarshalList(0x965465bd75220f94, s.List)
	return str
}

// Service_id_Params_Promise is a wrapper for a Service_id_Params promised by a client call.
type Service_id_Params_Promise struct{ *capnp.Pipeline }

func (p Service_id_Params_Promise) Struct() (Service_id_Params, error) {
	s, err := p.Pipeline.Struct()
	return Service_id_Params{s}, err
}

type Service_id_Results struct{ capnp.Struct }

// Service_id_Results_TypeID is the unique identifier for the type Service_id_Results.
const Service_id_Results_TypeID = 0xccdde1728f71e904

func NewService_id_Results(s *capnp.Segment) (Service_id_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_id_Results{st}, err
}

func NewRootService_id_Results(s *capnp.Segment) (Service_id_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_id_Results{st}, err
}

func ReadRootService_id_Results(msg *capnp.Message) (Service_id_Results, error) {
	root, err := msg.RootPtr()
	return Service_id_Results{root.Struct()}, err
}

func (s Service_id_Results) String() string {
	str, _ := text.Marshal(0xccdde1728f71e904, s.Struct)
	return str
}

func (s Service_id_Results) ServiceId() uint64 {
	return s.Struct.Uint64(0)
}

func (s Service_id_Results) SetServiceId(v uint64) {
	s.Struct.SetUint64(0, v)
}

// Service_id_Results_List is a list of Service_id_Results.
type Service_id_Results_List struct{ capnp.List }

// NewService_id_Results creates a new list of Service_id_Results.
func NewService_id_Results_List(s *capnp.Segment, sz int32) (Service_id_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return Service_id_Results_List{l}, err
}

func (s Service_id_Results_List) At(i int) Service_id_Results {
	return Service_id_Results{s.List.Struct(i)}
}

func (s Service_id_Results_List) Set(i int, v Service_id_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_id_Results_List) String() string {
	str, _ := text.MarshalList(0xccdde1728f71e904, s.List)
	return str
}

// Service_id_Results_Promise is a wrapper for a Service_id_Results promised by a client call.
type Service_id_Results_Promise struct{ *capnp.Pipeline }

func (p Service_id_Results_Promise) Struct() (Service_id_Results, error) {
	s, err := p.Pipeline.Struct()
	return Service_id_Results{s}, err
}

type Service_logLevel_Params struct{ capnp.Struct }

// Service_logLevel_Params_TypeID is the unique identifier for the type Service_logLevel_Params.
const Service_logLevel_Params_TypeID = 0xa6b9c11c2aac9785

func NewService_logLevel_Params(s *capnp.Segment) (Service_logLevel_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_logLevel_Params{st}, err
}

func NewRootService_logLevel_Params(s *capnp.Segment) (Service_logLevel_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_logLevel_Params{st}, err
}

func ReadRootService_logLevel_Params(msg *capnp.Message) (Service_logLevel_Params, error) {
	root, err := msg.RootPtr()
	return Service_logLevel_Params{root.Struct()}, err
}

func (s Service_logLevel_Params) String() string {
	str, _ := text.Marshal(0xa6b9c11c2aac9785, s.Struct)
	return str
}

// Service_logLevel_Params_List is a list of Service_logLevel_Params.
type Service_logLevel_Params_List struct{ capnp.List }

// NewService_logLevel_Params creates a new list of Service_logLevel_Params.
func NewService_logLevel_Params_List(s *capnp.Segment, sz int32) (Service_logLevel_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Service_logLevel_Params_List{l}, err
}

func (s Service_logLevel_Params_List) At(i int) Service_logLevel_Params {
	return Service_logLevel_Params{s.List.Struct(i)}
}

func (s Service_logLevel_Params_List) Set(i int, v Service_logLevel_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_logLevel_Params_List) String() string {
	str, _ := text.MarshalList(0xa6b9c11c2aac9785, s.List)
	return str
}

// Service_logLevel_Params_Promise is a wrapper for a Service_logLevel_Params promised by a client call.
type Service_logLevel_Params_Promise struct{ *capnp.Pipeline }

func (p Service_logLevel_Params_Promise) Struct() (Service_logLevel_Params, error) {
	s, err := p.Pipeline.Struct()
	return Service_logLevel_Params{s}, err
}

type Service_logLevel_Results struct{ capnp.Struct }

// Service_logLevel_Results_TypeID is the unique identifier for the type Service_logLevel_Results.
const Service_logLevel_Results_TypeID = 0x9285c4944dfb709f

func NewService_logLevel_Results(s *capnp.Segment) (Service_logLevel_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_logLevel_Results{st}, err
}

func NewRootService_logLevel_Results(s *capnp.Segment) (Service_logLevel_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_logLevel_Results{st}, err
}

func ReadRootService_logLevel_Results(msg *capnp.Message) (Service_logLevel_Results, error) {
	root, err := msg.RootPtr()
	return Service_logLevel_Results{root.Struct()}, err
}

func (s Service_logLevel_Results) String() string {
	str, _ := text.Marshal(0x9285c4944dfb709f, s.Struct)
	return str
}

func (s Service_logLevel_Results) Level() LogLevel {
	return LogLevel(s.Struct.Uint16(0))
}

func (s Service_logLevel_Results) SetLevel(v LogLevel) {
	s.Struct.SetUint16(0, uint16(v))
}

// Service_logLevel_Results_List is a list of Service_logLevel_Results.
type Service_logLevel_Results_List struct{ capnp.List }

// NewService_logLevel_Results creates a new list of Service_logLevel_Results.
func NewService_logLevel_Results_List(s *capnp.Segment, sz int32) (Service_logLevel_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return Service_logLevel_Results_List{l}, err
}

func (s Service_logLevel_Results_List) At(i int) Service_logLevel_Results {
	return Service_logLevel_Results{s.List.Struct(i)}
}

func (s Service_logLevel_Results_List) Set(i int, v Service_logLevel_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_logLevel_Results_List) String() string {
	str, _ := text.MarshalList(0x9285c4944dfb709f, s.List)
	return str
}

// Service_logLevel_Results_Promise is a wrapper for a Service_logLevel_Results promised by a client call.
type Service_logLevel_Results_Promise struct{ *capnp.Pipeline }

func (p Service_logLevel_Results_Promise) Struct() (Service_logLevel_Results, error) {
	s, err := p.Pipeline.Struct()
	return Service_logLevel_Results{s}, err
}

type Service_alive_Params struct{ capnp.Struct }

// Service_alive_Params_TypeID is the unique identifier for the type Service_alive_Params.
const Service_alive_Params_TypeID = 0x91dfcb778d8d16c0

func NewService_alive_Params(s *capnp.Segment) (Service_alive_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_alive_Params{st}, err
}

func NewRootService_alive_Params(s *capnp.Segment) (Service_alive_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_alive_Params{st}, err
}

func ReadRootService_alive_Params(msg *capnp.Message) (Service_alive_Params, error) {
	root, err := msg.RootPtr()
	return Service_alive_Params{root.Struct()}, err
}

func (s Service_alive_Params) String() string {
	str, _ := text.Marshal(0x91dfcb778d8d16c0, s.Struct)
	return str
}

// Service_alive_Params_List is a list of Service_alive_Params.
type Service_alive_Params_List struct{ capnp.List }

// NewService_alive_Params creates a new list of Service_alive_Params.
func NewService_alive_Params_List(s *capnp.Segment, sz int32) (Service_alive_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Service_alive_Params_List{l}, err
}

func (s Service_alive_Params_List) At(i int) Service_alive_Params {
	return Service_alive_Params{s.List.Struct(i)}
}

func (s Service_alive_Params_List) Set(i int, v Service_alive_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_alive_Params_List) String() string {
	str, _ := text.MarshalList(0x91dfcb778d8d16c0, s.List)
	return str
}

// Service_alive_Params_Promise is a wrapper for a Service_alive_Params promised by a client call.
type Service_alive_Params_Promise struct{ *capnp.Pipeline }

func (p Service_alive_Params_Promise) Struct() (Service_alive_Params, error) {
	s, err := p.Pipeline.Struct()
	return Service_alive_Params{s}, err
}

type Service_alive_Results struct{ capnp.Struct }

// Service_alive_Results_TypeID is the unique identifier for the type Service_alive_Results.
const Service_alive_Results_TypeID = 0xe542d95b68592c1c

func NewService_alive_Results(s *capnp.Segment) (Service_alive_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_alive_Results{st}, err
}

func NewRootService_alive_Results(s *capnp.Segment) (Service_alive_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_alive_Results{st}, err
}

func ReadRootService_alive_Results(msg *capnp.Message) (Service_alive_Results, error) {
	root, err := msg.RootPtr()
	return Service_alive_Results{root.Struct()}, err
}

func (s Service_alive_Results) String() string {
	str, _ := text.Marshal(0xe542d95b68592c1c, s.Struct)
	return str
}

func (s Service_alive_Results) Alive() bool {
	return s.Struct.Bit(0)
}

func (s Service_alive_Results) SetAlive(v bool) {
	s.Struct.SetBit(0, v)
}

// Service_alive_Results_List is a list of Service_alive_Results.
type Service_alive_Results_List struct{ capnp.List }

// NewService_alive_Results creates a new list of Service_alive_Results.
func NewService_alive_Results_List(s *capnp.Segment, sz int32) (Service_alive_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return Service_alive_Results_List{l}, err
}

func (s Service_alive_Results_List) At(i int) Service_alive_Results {
	return Service_alive_Results{s.List.Struct(i)}
}

func (s Service_alive_Results_List) Set(i int, v Service_alive_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_alive_Results_List) String() string {
	str, _ := text.MarshalList(0xe542d95b68592c1c, s.List)
	return str
}

// Service_alive_Results_Promise is a wrapper for a Service_alive_Results promised by a client call.
type Service_alive_Results_Promise struct{ *capnp.Pipeline }

func (p Service_alive_Results_Promise) Struct() (Service_alive_Results, error) {
	s, err := p.Pipeline.Struct()
	return Service_alive_Results{s}, err
}

type Service_kill_Params struct{ capnp.Struct }

// Service_kill_Params_TypeID is the unique identifier for the type Service_kill_Params.
const Service_kill_Params_TypeID = 0xe3ec490c3d4015bb

func NewService_kill_Params(s *capnp.Segment) (Service_kill_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_kill_Params{st}, err
}

func NewRootService_kill_Params(s *capnp.Segment) (Service_kill_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_kill_Params{st}, err
}

func ReadRootService_kill_Params(msg *capnp.Message) (Service_kill_Params, error) {
	root, err := msg.RootPtr()
	return Service_kill_Params{root.Struct()}, err
}

func (s Service_kill_Params) String() string {
	str, _ := text.Marshal(0xe3ec490c3d4015bb, s.Struct)
	return str
}

// Service_kill_Params_List is a list of Service_kill_Params.
type Service_kill_Params_List struct{ capnp.List }

// NewService_kill_Params creates a new list of Service_kill_Params.
func NewService_kill_Params_List(s *capnp.Segment, sz int32) (Service_kill_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Service_kill_Params_List{l}, err
}

func (s Service_kill_Params_List) At(i int) Service_kill_Params {
	return Service_kill_Params{s.List.Struct(i)}
}

func (s Service_kill_Params_List) Set(i int, v Service_kill_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_kill_Params_List) String() string {
	str, _ := text.MarshalList(0xe3ec490c3d4015bb, s.List)
	return str
}

// Service_kill_Params_Promise is a wrapper for a Service_kill_Params promised by a client call.
type Service_kill_Params_Promise struct{ *capnp.Pipeline }

func (p Service_kill_Params_Promise) Struct() (Service_kill_Params, error) {
	s, err := p.Pipeline.Struct()
	return Service_kill_Params{s}, err
}

type Service_kill_Results struct{ capnp.Struct }

// Service_kill_Results_TypeID is the unique identifier for the type Service_kill_Results.
const Service_kill_Results_TypeID = 0xf95512d6a5f5e530

func NewService_kill_Results(s *capnp.Segment) (Service_kill_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_kill_Results{st}, err
}

func NewRootService_kill_Results(s *capnp.Segment) (Service_kill_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_kill_Results{st}, err
}

func ReadRootService_kill_Results(msg *capnp.Message) (Service_kill_Results, error) {
	root, err := msg.RootPtr()
	return Service_kill_Results{root.Struct()}, err
}

func (s Service_kill_Results) String() string {
	str, _ := text.Marshal(0xf95512d6a5f5e530, s.Struct)
	return str
}

// Service_kill_Results_List is a list of Service_kill_Results.
type Service_kill_Results_List struct{ capnp.List }

// NewService_kill_Results creates a new list of Service_kill_Results.
func NewService_kill_Results_List(s *capnp.Segment, sz int32) (Service_kill_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Service_kill_Results_List{l}, err
}

func (s Service_kill_Results_List) At(i int) Service_kill_Results {
	return Service_kill_Results{s.List.Struct(i)}
}

func (s Service_kill_Results_List) Set(i int, v Service_kill_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_kill_Results_List) String() string {
	str, _ := text.MarshalList(0xf95512d6a5f5e530, s.List)
	return str
}

// Service_kill_Results_Promise is a wrapper for a Service_kill_Results promised by a client call.
type Service_kill_Results_Promise struct{ *capnp.Pipeline }

func (p Service_kill_Results_Promise) Struct() (Service_kill_Results, error) {
	s, err := p.Pipeline.Struct()
	return Service_kill_Results{s}, err
}

const schema_db8274f9144abc7e = "x\xda\x9cV\x7fl\x13\xe5\x1b\x7f\x9e\xbb{{_\x96" +
	"m\xe5\xed\x0d\xf2\xe5\x87\x96\x99a`q\xfc\xd8\xf4\x0f" +
	"H\xc8\xda%$v\x99\xa1-\x10\x05\xe2\x1f'=\xc7" +
	"\xc5\xae+w\xdd\xc8\x90\xa8\x90\xed\x0fc\x96\xc5\x09." +
	",Qc\xc2\x88$\xa8\xa0\xc1\x84\xc8D\xa7#*\x0e" +
	"\x03Q\x11\x85 \xeab\xd4\xc58\x0c\xd1M\xf1\xcc{" +
	"\xed\xdb{\xbb\xb61\xf1\xaf6\xb9\xe7\xe7\xe7\xf9|\xde" +
	"\xe7Y\xb3@\x0eIk\xc9\xeb\x15\x00\xb1}\xc4w{" +
	"\xf7\x83#KN}\xdfK\xab\x11@Q\x01\xb4\x0d\xe4" +
	"&(\xce\xe5)\xdfD\xcdC\xd3\x03\xe0}\xa8%\xb3" +
	"\xa08SU\xa3\xe3\xa4\xf7\x8f\x01\x88Uc\xeeK\x13" +
	"!\x12\x02j\xf3H3\xa0\xf3\xee\xc2\xfe\xfe=\xe7\xaf" +
	"?\x0b4\xc0=\x1b\\\xcf\x97\xd2\x7f>p\xf0\x83\xbe" +
	"A\x88\x05\xf2\x9e\x94,f\x9e\x8b\\O\xfb\xadp\x7f" +
	"\xf2\xb7#\x83b\xe8u\xd9\xd0\x1b\\\x83\x83\xfe\xbb\xba" +
	"F\x8d-\xcf\x0b\xa1u\xf2-(\xd7\x03m\xcb\xceU" +
	"(#\x9e\x9f\xb6\x91\xfc\x04\xa8E\\\xb7/\xaf\xb6]" +
	"=2\xdd9\"\xf4b\x921P\x9c\xbe\xa1\xe3\xf5K" +
	"\xdf;}\xd4\x8b\xd7\x14!\x01\x04\xe5w3\xed\xdc\x7f" +
	"g\xe0\x98\xe7\xb0\xd6E\x85\x9c\x9d\x18\xfb+\xb8\xf9\xb8" +
	"\x10i\x01\xf9\x0a\x14\xe7\xec}\xe7\xff~\x7f\xf9\xae\xd7" +
	"\x84\xd2\xb5\x19e\x16P\xbb\xad\xb0\x12\xee}\xaefj" +
	"ix\xc7\x1b@+d\xe7\x893\xad53\x99\x03_" +
	"\x03\xa0v\x07\x19\xd4\x96\x13\x96\xb9\x96\xa8\xa8\x8d\xb3\xbf" +
	"\xce\xc3\x0d\xab\xb7\x0f-\x91Oe\xd3\x10d\xd1^%" +
	",\xdaI\xb7\xa1\xe5\x95'\x0e\x9c\xb8{\xcbi\xaf\x8c" +
	"\xa6\xcfI\x0b\x82\xe2\xf4\x9c\xd9\xdb\xba\xf6\xc2\xd1w\x84" +
	"\x02G]\xf0\x95\x1fw\x0fX7\xae}\"\x80\xaf\xbd" +
	"\xecb4\xe2\x86\xfcex\xef\xd0+\xf5O]\x00Z" +
	"!\x15\x14\xf8\x11\x19\xd6.\xb2\xaa\xb4\x09\xd2\x0e\xe8\x9c" +
	"{|\xcb\xec\x8a\x95\xdb.\x89\x9dN\x93\x8f\x01\xb5[" +
	"n\xa0\xc8\xc2\xd5/~\xb8\xdf\xfeL\x84\xc8w\x09\x14" +
	"\xe7\xed\x05\xa1\x0d\x95\x91\xa9\xef\x84\xe1\xcd\xb8\xa0.\xbd" +
	"g\xdb\xae\x1dWZ&E^\\\xcb\x8e\xfd\x86\x1br" +
	"\xec\xd0\xa6\xcb\xfbzv\xfd,\xc0\xd1\x84\xbeVfP" +
	"\xe5c\x06\x87\xe9\x9b\xbd\xdf\xfc\x10\xff\xb5\x08\xdd\xb0\xcf" +
	"\xd26\xfa\x98}\xd8\xa7J\xdaa\x95\xa1\xbbf\xf2\xd6" +
	"\xc8\x17\x81\xad3B!\xfbU\x86QUO\xc73\xf3" +
	"?\x0d\xcf\x8a\xb0\x1b\xeaM@\xcdT\x9b\xa1\xc1\xd1\xd3" +
	"\xe9U;\xf5tJJ\xaf\x0f\xa7\xd3\xab\xcc\x94\x9d\xd1" +
	"S;\x8d\xbahP\xb7\xf4\x0e{\xeew;\xa3[\x19" +
	"#\xb1)U\xd7\x1c-4\x90\xe7\x1a\xc4\x0d\xbb+\x99" +
	"\xb1!\xa6\xc8\x0a\x80\x82\x00\xb4*\x0e\x10\xab\x941\xf6" +
	"\x7f\x09\x1dn\x09\x98B\x02\x12\x12@1\xdbf\xc3\xea" +
	"6w\x1a\xab\xf4\xa4\xd9m\x94\xca\xc6\x0d\x92\x9d\xedm" +
	"F\xb7\x91\xcc&\x943\xb6\x98\xb0\x11 \xf6?\x19c" +
	"5\x12\x06\x93\xcc\x0a\xfd\x1e-\x00\xd1/$\xcdu`" +
	"\x19IC\xb7\x8dH\xe2_;\xe0\x96\x80\x09\x9c\x07\x12" +
	"\xce+\xdd\x81\x99\xa8\x8b\xea\x96Z\x0a\xcd\xacE]T" +
	"\xf7\xb3\xee\xc4<\x8b\xbd\xc2e\xb38\xbc/7.7" +
	"\xb4\xdea\x03\xffP\x02\x17\xd7\x02\x8b\x92{\xdfK\x8f" +
	"\xfa13\xe9aZ\xd69\xde\x9c\x05\xe9\xbf\x82\x8e\xbc" +
	"`4\xa2\x88\xb1\xf92\x01\xc8\xbf\x89\xc8\x15Nw/" +
	"\x06\x89\x1a*b\xfe}C\xfe\xf4\xd2m\xad \xd1\x98" +
	"\x8aR\xfe\x99F.?\xba\xb1\x11$\xbaNE9/" +
	"U\xe4R\xa1\x0d\xf5 \xd1ZU6\x13!txC" +
	"\x00\x10\xc2\xa0K\xba\x10\xfa\x19\x06!\x8c\"\x96\xd5I" +
	"\xa9\xfe\xb7\x0b\x1c\xe1\x86 G\x12X\x09\x12V\x0a\xcd" +
	"\xab\x9cq\xed\xa6\x9d1,#\x91\x9b\x9d]<\xd5B" +
	"f\xce\x95C!\xdb\xe2\x86\xed\x9f[S\x81\xf2\xb2\xa6" +
	"%y\x8b\xe9\xf5m.\x14\xb2\x91t\x07\x82\x12\x00]" +
	"\xd9\xc8\xe6Fk\xeb\x01P\xa2\x8b\xd8\x8fLi#@" +
	"0a<\xd2\xd5\xee7S\x8fv\xfa\xf7\xe8V*h" +
	"XV\xa7U\x84\x96\xa7%(G\x14=\x9d\x8e\x94\x94" +
	"Q\x9e\x8b%x\xcc\x9b\xce~\x0f\x96}#\xb2\x8fH" +
	")=\x17\x94\xc0\xac\x10AB\x14JP\xca\x0e\xa9d" +
	"O|\xf8+D\xa0\xe5\x84\x8d\xd5\x80Q\x19\xdd\x0e\xab" +
	"\x85\xf0\x10t\xe33\xac\x97\xb9\xe4\xe7\x9b\x1d\xf9V\xa2" +
	"\xd3\x8c\xfc\x93\x8c\xfc|\x15\"?+\xe8\x958H\xf4" +
	"\xa2\x8a\x12?z\x84E;\xce\x841\xca\xc8\xcf/\x1f" +
	"\xe4\x97\x0e=\xc9\xfc\x8e\xa9\x98?\x0b\xbcuO_`" +
	"~\x87T$\xf9\xa5\x8c|]\xd1\xa7\x87A\xa2}*" +
	"\xfa\xf8}\"l\x98\x9e\x16\x90h\x87\x8aj~a\"" +
	"?.\xa8\xce\xc4\xb65'6\xe1\xe1\x0c\x09\x12a\xd2" +
	"\x13\xd7\xc2\\Y:|\x06\xc8\x87 \x1bv\x08\x9f\xcc" +
	"\xc1\\N\xaf\x05$\xe1z-\xf7\x14\xc7\x8d`\x91\x9e" +
	"[<\x8e\xf0\\H\xbd\xf3\x87)\x03\xf0\x9f\x00\x00\x00" +
	"\xff\xff\xc7>\x0d\xf2"

func init() {
	schemas.Register(schema_db8274f9144abc7e,
		0x84e4b51ba5570071,
		0x8ff15814cd06ecd7,
		0x8ff88405c5bd0dec,
		0x91dfcb778d8d16c0,
		0x9285c4944dfb709f,
		0x92a4f36c8d41b673,
		0x965465bd75220f94,
		0xa504000ac6204c12,
		0xa56ff1a4dc4cdcd8,
		0xa6b9c11c2aac9785,
		0xa9121e4800ff7069,
		0xac531ffcc2cdbf05,
		0xae6825c3fecb35bf,
		0xb25b411cec149334,
		0xb5031b975a2f2d5d,
		0xb95426b082b00c25,
		0xbea6ce314a7abc79,
		0xccdde1728f71e904,
		0xce802aa8977a9aee,
		0xd2592928fa547bc6,
		0xd47381c89e2f1649,
		0xe3ec490c3d4015bb,
		0xe542d95b68592c1c,
		0xeb68797cd74f95c2,
		0xf052e7e084b31199,
		0xf95512d6a5f5e530,
		0xfa41cf108b6d790d)
}
