// Code generated by capnpc-go. DO NOT EDIT.

package capnprpc

import (
	context "golang.org/x/net/context"
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
	server "zombiezen.com/go/capnproto2/server"
)

type App struct{ Client capnp.Client }

// App_TypeID is the unique identifier for the type App.
const App_TypeID = 0xf052e7e084b31199

func (c App) Id(ctx context.Context, params func(App_id_Params) error, opts ...capnp.CallOption) App_id_Results_Promise {
	if c.Client == nil {
		return App_id_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      0,
			InterfaceName: "app.capnp:App",
			MethodName:    "id",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_id_Params{Struct: s}) }
	}
	return App_id_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) Instance(ctx context.Context, params func(App_instance_Params) error, opts ...capnp.CallOption) App_instance_Results_Promise {
	if c.Client == nil {
		return App_instance_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      1,
			InterfaceName: "app.capnp:App",
			MethodName:    "instance",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_instance_Params{Struct: s}) }
	}
	return App_instance_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) StartedOn(ctx context.Context, params func(App_startedOn_Params) error, opts ...capnp.CallOption) App_startedOn_Results_Promise {
	if c.Client == nil {
		return App_startedOn_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      2,
			InterfaceName: "app.capnp:App",
			MethodName:    "startedOn",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_startedOn_Params{Struct: s}) }
	}
	return App_startedOn_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) LogLevel(ctx context.Context, params func(App_logLevel_Params) error, opts ...capnp.CallOption) App_logLevel_Results_Promise {
	if c.Client == nil {
		return App_logLevel_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      3,
			InterfaceName: "app.capnp:App",
			MethodName:    "logLevel",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_logLevel_Params{Struct: s}) }
	}
	return App_logLevel_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) RegisteredServices(ctx context.Context, params func(App_registeredServices_Params) error, opts ...capnp.CallOption) App_registeredServices_Results_Promise {
	if c.Client == nil {
		return App_registeredServices_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      4,
			InterfaceName: "app.capnp:App",
			MethodName:    "registeredServices",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_registeredServices_Params{Struct: s}) }
	}
	return App_registeredServices_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) Service(ctx context.Context, params func(App_service_Params) error, opts ...capnp.CallOption) App_service_Results_Promise {
	if c.Client == nil {
		return App_service_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      5,
			InterfaceName: "app.capnp:App",
			MethodName:    "service",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_service_Params{Struct: s}) }
	}
	return App_service_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c App) Kill(ctx context.Context, params func(App_kill_Params) error, opts ...capnp.CallOption) App_kill_Results_Promise {
	if c.Client == nil {
		return App_kill_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      6,
			InterfaceName: "app.capnp:App",
			MethodName:    "kill",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(App_kill_Params{Struct: s}) }
	}
	return App_kill_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}

type App_Server interface {
	Id(App_id) error

	Instance(App_instance) error

	StartedOn(App_startedOn) error

	LogLevel(App_logLevel) error

	RegisteredServices(App_registeredServices) error

	Service(App_service) error

	Kill(App_kill) error
}

func App_ServerToClient(s App_Server) App {
	c, _ := s.(server.Closer)
	return App{Client: server.New(App_Methods(nil, s), c)}
}

func App_Methods(methods []server.Method, s App_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 7)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      0,
			InterfaceName: "app.capnp:App",
			MethodName:    "id",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_id{c, opts, App_id_Params{Struct: p}, App_id_Results{Struct: r}}
			return s.Id(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      1,
			InterfaceName: "app.capnp:App",
			MethodName:    "instance",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_instance{c, opts, App_instance_Params{Struct: p}, App_instance_Results{Struct: r}}
			return s.Instance(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      2,
			InterfaceName: "app.capnp:App",
			MethodName:    "startedOn",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_startedOn{c, opts, App_startedOn_Params{Struct: p}, App_startedOn_Results{Struct: r}}
			return s.StartedOn(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      3,
			InterfaceName: "app.capnp:App",
			MethodName:    "logLevel",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_logLevel{c, opts, App_logLevel_Params{Struct: p}, App_logLevel_Results{Struct: r}}
			return s.LogLevel(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      4,
			InterfaceName: "app.capnp:App",
			MethodName:    "registeredServices",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_registeredServices{c, opts, App_registeredServices_Params{Struct: p}, App_registeredServices_Results{Struct: r}}
			return s.RegisteredServices(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      5,
			InterfaceName: "app.capnp:App",
			MethodName:    "service",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_service{c, opts, App_service_Params{Struct: p}, App_service_Results{Struct: r}}
			return s.Service(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf052e7e084b31199,
			MethodID:      6,
			InterfaceName: "app.capnp:App",
			MethodName:    "kill",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := App_kill{c, opts, App_kill_Params{Struct: p}, App_kill_Results{Struct: r}}
			return s.Kill(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 0},
	})

	return methods
}

// App_id holds the arguments for a server call to App.id.
type App_id struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_id_Params
	Results App_id_Results
}

// App_instance holds the arguments for a server call to App.instance.
type App_instance struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_instance_Params
	Results App_instance_Results
}

// App_startedOn holds the arguments for a server call to App.startedOn.
type App_startedOn struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_startedOn_Params
	Results App_startedOn_Results
}

// App_logLevel holds the arguments for a server call to App.logLevel.
type App_logLevel struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_logLevel_Params
	Results App_logLevel_Results
}

// App_registeredServices holds the arguments for a server call to App.registeredServices.
type App_registeredServices struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_registeredServices_Params
	Results App_registeredServices_Results
}

// App_service holds the arguments for a server call to App.service.
type App_service struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_service_Params
	Results App_service_Results
}

// App_kill holds the arguments for a server call to App.kill.
type App_kill struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  App_kill_Params
	Results App_kill_Results
}

type App_id_Params struct{ capnp.Struct }

// App_id_Params_TypeID is the unique identifier for the type App_id_Params.
const App_id_Params_TypeID = 0xa56ff1a4dc4cdcd8

func NewApp_id_Params(s *capnp.Segment) (App_id_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_id_Params{st}, err
}

func NewRootApp_id_Params(s *capnp.Segment) (App_id_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_id_Params{st}, err
}

func ReadRootApp_id_Params(msg *capnp.Message) (App_id_Params, error) {
	root, err := msg.RootPtr()
	return App_id_Params{root.Struct()}, err
}

func (s App_id_Params) String() string {
	str, _ := text.Marshal(0xa56ff1a4dc4cdcd8, s.Struct)
	return str
}

// App_id_Params_List is a list of App_id_Params.
type App_id_Params_List struct{ capnp.List }

// NewApp_id_Params creates a new list of App_id_Params.
func NewApp_id_Params_List(s *capnp.Segment, sz int32) (App_id_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_id_Params_List{l}, err
}

func (s App_id_Params_List) At(i int) App_id_Params { return App_id_Params{s.List.Struct(i)} }

func (s App_id_Params_List) Set(i int, v App_id_Params) error { return s.List.SetStruct(i, v.Struct) }

func (s App_id_Params_List) String() string {
	str, _ := text.MarshalList(0xa56ff1a4dc4cdcd8, s.List)
	return str
}

// App_id_Params_Promise is a wrapper for a App_id_Params promised by a client call.
type App_id_Params_Promise struct{ *capnp.Pipeline }

func (p App_id_Params_Promise) Struct() (App_id_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_id_Params{s}, err
}

type App_id_Results struct{ capnp.Struct }

// App_id_Results_TypeID is the unique identifier for the type App_id_Results.
const App_id_Results_TypeID = 0xd2592928fa547bc6

func NewApp_id_Results(s *capnp.Segment) (App_id_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_id_Results{st}, err
}

func NewRootApp_id_Results(s *capnp.Segment) (App_id_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_id_Results{st}, err
}

func ReadRootApp_id_Results(msg *capnp.Message) (App_id_Results, error) {
	root, err := msg.RootPtr()
	return App_id_Results{root.Struct()}, err
}

func (s App_id_Results) String() string {
	str, _ := text.Marshal(0xd2592928fa547bc6, s.Struct)
	return str
}

func (s App_id_Results) AppId() uint64 {
	return s.Struct.Uint64(0)
}

func (s App_id_Results) SetAppId(v uint64) {
	s.Struct.SetUint64(0, v)
}

// App_id_Results_List is a list of App_id_Results.
type App_id_Results_List struct{ capnp.List }

// NewApp_id_Results creates a new list of App_id_Results.
func NewApp_id_Results_List(s *capnp.Segment, sz int32) (App_id_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return App_id_Results_List{l}, err
}

func (s App_id_Results_List) At(i int) App_id_Results { return App_id_Results{s.List.Struct(i)} }

func (s App_id_Results_List) Set(i int, v App_id_Results) error { return s.List.SetStruct(i, v.Struct) }

func (s App_id_Results_List) String() string {
	str, _ := text.MarshalList(0xd2592928fa547bc6, s.List)
	return str
}

// App_id_Results_Promise is a wrapper for a App_id_Results promised by a client call.
type App_id_Results_Promise struct{ *capnp.Pipeline }

func (p App_id_Results_Promise) Struct() (App_id_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_id_Results{s}, err
}

type App_instance_Params struct{ capnp.Struct }

// App_instance_Params_TypeID is the unique identifier for the type App_instance_Params.
const App_instance_Params_TypeID = 0xbea6ce314a7abc79

func NewApp_instance_Params(s *capnp.Segment) (App_instance_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_instance_Params{st}, err
}

func NewRootApp_instance_Params(s *capnp.Segment) (App_instance_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_instance_Params{st}, err
}

func ReadRootApp_instance_Params(msg *capnp.Message) (App_instance_Params, error) {
	root, err := msg.RootPtr()
	return App_instance_Params{root.Struct()}, err
}

func (s App_instance_Params) String() string {
	str, _ := text.Marshal(0xbea6ce314a7abc79, s.Struct)
	return str
}

// App_instance_Params_List is a list of App_instance_Params.
type App_instance_Params_List struct{ capnp.List }

// NewApp_instance_Params creates a new list of App_instance_Params.
func NewApp_instance_Params_List(s *capnp.Segment, sz int32) (App_instance_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_instance_Params_List{l}, err
}

func (s App_instance_Params_List) At(i int) App_instance_Params {
	return App_instance_Params{s.List.Struct(i)}
}

func (s App_instance_Params_List) Set(i int, v App_instance_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_instance_Params_List) String() string {
	str, _ := text.MarshalList(0xbea6ce314a7abc79, s.List)
	return str
}

// App_instance_Params_Promise is a wrapper for a App_instance_Params promised by a client call.
type App_instance_Params_Promise struct{ *capnp.Pipeline }

func (p App_instance_Params_Promise) Struct() (App_instance_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_instance_Params{s}, err
}

type App_instance_Results struct{ capnp.Struct }

// App_instance_Results_TypeID is the unique identifier for the type App_instance_Results.
const App_instance_Results_TypeID = 0x92a4f36c8d41b673

func NewApp_instance_Results(s *capnp.Segment) (App_instance_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_instance_Results{st}, err
}

func NewRootApp_instance_Results(s *capnp.Segment) (App_instance_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_instance_Results{st}, err
}

func ReadRootApp_instance_Results(msg *capnp.Message) (App_instance_Results, error) {
	root, err := msg.RootPtr()
	return App_instance_Results{root.Struct()}, err
}

func (s App_instance_Results) String() string {
	str, _ := text.Marshal(0x92a4f36c8d41b673, s.Struct)
	return str
}

func (s App_instance_Results) InstanceId() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s App_instance_Results) HasInstanceId() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s App_instance_Results) InstanceIdBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s App_instance_Results) SetInstanceId(v string) error {
	return s.Struct.SetText(0, v)
}

// App_instance_Results_List is a list of App_instance_Results.
type App_instance_Results_List struct{ capnp.List }

// NewApp_instance_Results creates a new list of App_instance_Results.
func NewApp_instance_Results_List(s *capnp.Segment, sz int32) (App_instance_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return App_instance_Results_List{l}, err
}

func (s App_instance_Results_List) At(i int) App_instance_Results {
	return App_instance_Results{s.List.Struct(i)}
}

func (s App_instance_Results_List) Set(i int, v App_instance_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_instance_Results_List) String() string {
	str, _ := text.MarshalList(0x92a4f36c8d41b673, s.List)
	return str
}

// App_instance_Results_Promise is a wrapper for a App_instance_Results promised by a client call.
type App_instance_Results_Promise struct{ *capnp.Pipeline }

func (p App_instance_Results_Promise) Struct() (App_instance_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_instance_Results{s}, err
}

type App_startedOn_Params struct{ capnp.Struct }

// App_startedOn_Params_TypeID is the unique identifier for the type App_startedOn_Params.
const App_startedOn_Params_TypeID = 0x84e4b51ba5570071

func NewApp_startedOn_Params(s *capnp.Segment) (App_startedOn_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_startedOn_Params{st}, err
}

func NewRootApp_startedOn_Params(s *capnp.Segment) (App_startedOn_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_startedOn_Params{st}, err
}

func ReadRootApp_startedOn_Params(msg *capnp.Message) (App_startedOn_Params, error) {
	root, err := msg.RootPtr()
	return App_startedOn_Params{root.Struct()}, err
}

func (s App_startedOn_Params) String() string {
	str, _ := text.Marshal(0x84e4b51ba5570071, s.Struct)
	return str
}

// App_startedOn_Params_List is a list of App_startedOn_Params.
type App_startedOn_Params_List struct{ capnp.List }

// NewApp_startedOn_Params creates a new list of App_startedOn_Params.
func NewApp_startedOn_Params_List(s *capnp.Segment, sz int32) (App_startedOn_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_startedOn_Params_List{l}, err
}

func (s App_startedOn_Params_List) At(i int) App_startedOn_Params {
	return App_startedOn_Params{s.List.Struct(i)}
}

func (s App_startedOn_Params_List) Set(i int, v App_startedOn_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_startedOn_Params_List) String() string {
	str, _ := text.MarshalList(0x84e4b51ba5570071, s.List)
	return str
}

// App_startedOn_Params_Promise is a wrapper for a App_startedOn_Params promised by a client call.
type App_startedOn_Params_Promise struct{ *capnp.Pipeline }

func (p App_startedOn_Params_Promise) Struct() (App_startedOn_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_startedOn_Params{s}, err
}

type App_startedOn_Results struct{ capnp.Struct }

// App_startedOn_Results_TypeID is the unique identifier for the type App_startedOn_Results.
const App_startedOn_Results_TypeID = 0xb5031b975a2f2d5d

func NewApp_startedOn_Results(s *capnp.Segment) (App_startedOn_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_startedOn_Results{st}, err
}

func NewRootApp_startedOn_Results(s *capnp.Segment) (App_startedOn_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_startedOn_Results{st}, err
}

func ReadRootApp_startedOn_Results(msg *capnp.Message) (App_startedOn_Results, error) {
	root, err := msg.RootPtr()
	return App_startedOn_Results{root.Struct()}, err
}

func (s App_startedOn_Results) String() string {
	str, _ := text.Marshal(0xb5031b975a2f2d5d, s.Struct)
	return str
}

func (s App_startedOn_Results) StartedOn() int64 {
	return int64(s.Struct.Uint64(0))
}

func (s App_startedOn_Results) SetStartedOn(v int64) {
	s.Struct.SetUint64(0, uint64(v))
}

// App_startedOn_Results_List is a list of App_startedOn_Results.
type App_startedOn_Results_List struct{ capnp.List }

// NewApp_startedOn_Results creates a new list of App_startedOn_Results.
func NewApp_startedOn_Results_List(s *capnp.Segment, sz int32) (App_startedOn_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return App_startedOn_Results_List{l}, err
}

func (s App_startedOn_Results_List) At(i int) App_startedOn_Results {
	return App_startedOn_Results{s.List.Struct(i)}
}

func (s App_startedOn_Results_List) Set(i int, v App_startedOn_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_startedOn_Results_List) String() string {
	str, _ := text.MarshalList(0xb5031b975a2f2d5d, s.List)
	return str
}

// App_startedOn_Results_Promise is a wrapper for a App_startedOn_Results promised by a client call.
type App_startedOn_Results_Promise struct{ *capnp.Pipeline }

func (p App_startedOn_Results_Promise) Struct() (App_startedOn_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_startedOn_Results{s}, err
}

type App_logLevel_Params struct{ capnp.Struct }

// App_logLevel_Params_TypeID is the unique identifier for the type App_logLevel_Params.
const App_logLevel_Params_TypeID = 0x8ff15814cd06ecd7

func NewApp_logLevel_Params(s *capnp.Segment) (App_logLevel_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_logLevel_Params{st}, err
}

func NewRootApp_logLevel_Params(s *capnp.Segment) (App_logLevel_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_logLevel_Params{st}, err
}

func ReadRootApp_logLevel_Params(msg *capnp.Message) (App_logLevel_Params, error) {
	root, err := msg.RootPtr()
	return App_logLevel_Params{root.Struct()}, err
}

func (s App_logLevel_Params) String() string {
	str, _ := text.Marshal(0x8ff15814cd06ecd7, s.Struct)
	return str
}

// App_logLevel_Params_List is a list of App_logLevel_Params.
type App_logLevel_Params_List struct{ capnp.List }

// NewApp_logLevel_Params creates a new list of App_logLevel_Params.
func NewApp_logLevel_Params_List(s *capnp.Segment, sz int32) (App_logLevel_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_logLevel_Params_List{l}, err
}

func (s App_logLevel_Params_List) At(i int) App_logLevel_Params {
	return App_logLevel_Params{s.List.Struct(i)}
}

func (s App_logLevel_Params_List) Set(i int, v App_logLevel_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_logLevel_Params_List) String() string {
	str, _ := text.MarshalList(0x8ff15814cd06ecd7, s.List)
	return str
}

// App_logLevel_Params_Promise is a wrapper for a App_logLevel_Params promised by a client call.
type App_logLevel_Params_Promise struct{ *capnp.Pipeline }

func (p App_logLevel_Params_Promise) Struct() (App_logLevel_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_logLevel_Params{s}, err
}

type App_logLevel_Results struct{ capnp.Struct }

// App_logLevel_Results_TypeID is the unique identifier for the type App_logLevel_Results.
const App_logLevel_Results_TypeID = 0x8ff88405c5bd0dec

func NewApp_logLevel_Results(s *capnp.Segment) (App_logLevel_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_logLevel_Results{st}, err
}

func NewRootApp_logLevel_Results(s *capnp.Segment) (App_logLevel_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_logLevel_Results{st}, err
}

func ReadRootApp_logLevel_Results(msg *capnp.Message) (App_logLevel_Results, error) {
	root, err := msg.RootPtr()
	return App_logLevel_Results{root.Struct()}, err
}

func (s App_logLevel_Results) String() string {
	str, _ := text.Marshal(0x8ff88405c5bd0dec, s.Struct)
	return str
}

func (s App_logLevel_Results) Level() LogLevel {
	return LogLevel(s.Struct.Uint16(0))
}

func (s App_logLevel_Results) SetLevel(v LogLevel) {
	s.Struct.SetUint16(0, uint16(v))
}

// App_logLevel_Results_List is a list of App_logLevel_Results.
type App_logLevel_Results_List struct{ capnp.List }

// NewApp_logLevel_Results creates a new list of App_logLevel_Results.
func NewApp_logLevel_Results_List(s *capnp.Segment, sz int32) (App_logLevel_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return App_logLevel_Results_List{l}, err
}

func (s App_logLevel_Results_List) At(i int) App_logLevel_Results {
	return App_logLevel_Results{s.List.Struct(i)}
}

func (s App_logLevel_Results_List) Set(i int, v App_logLevel_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_logLevel_Results_List) String() string {
	str, _ := text.MarshalList(0x8ff88405c5bd0dec, s.List)
	return str
}

// App_logLevel_Results_Promise is a wrapper for a App_logLevel_Results promised by a client call.
type App_logLevel_Results_Promise struct{ *capnp.Pipeline }

func (p App_logLevel_Results_Promise) Struct() (App_logLevel_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_logLevel_Results{s}, err
}

type App_registeredServices_Params struct{ capnp.Struct }

// App_registeredServices_Params_TypeID is the unique identifier for the type App_registeredServices_Params.
const App_registeredServices_Params_TypeID = 0xa9121e4800ff7069

func NewApp_registeredServices_Params(s *capnp.Segment) (App_registeredServices_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_registeredServices_Params{st}, err
}

func NewRootApp_registeredServices_Params(s *capnp.Segment) (App_registeredServices_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_registeredServices_Params{st}, err
}

func ReadRootApp_registeredServices_Params(msg *capnp.Message) (App_registeredServices_Params, error) {
	root, err := msg.RootPtr()
	return App_registeredServices_Params{root.Struct()}, err
}

func (s App_registeredServices_Params) String() string {
	str, _ := text.Marshal(0xa9121e4800ff7069, s.Struct)
	return str
}

// App_registeredServices_Params_List is a list of App_registeredServices_Params.
type App_registeredServices_Params_List struct{ capnp.List }

// NewApp_registeredServices_Params creates a new list of App_registeredServices_Params.
func NewApp_registeredServices_Params_List(s *capnp.Segment, sz int32) (App_registeredServices_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_registeredServices_Params_List{l}, err
}

func (s App_registeredServices_Params_List) At(i int) App_registeredServices_Params {
	return App_registeredServices_Params{s.List.Struct(i)}
}

func (s App_registeredServices_Params_List) Set(i int, v App_registeredServices_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_registeredServices_Params_List) String() string {
	str, _ := text.MarshalList(0xa9121e4800ff7069, s.List)
	return str
}

// App_registeredServices_Params_Promise is a wrapper for a App_registeredServices_Params promised by a client call.
type App_registeredServices_Params_Promise struct{ *capnp.Pipeline }

func (p App_registeredServices_Params_Promise) Struct() (App_registeredServices_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_registeredServices_Params{s}, err
}

type App_registeredServices_Results struct{ capnp.Struct }

// App_registeredServices_Results_TypeID is the unique identifier for the type App_registeredServices_Results.
const App_registeredServices_Results_TypeID = 0xae6825c3fecb35bf

func NewApp_registeredServices_Results(s *capnp.Segment) (App_registeredServices_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_registeredServices_Results{st}, err
}

func NewRootApp_registeredServices_Results(s *capnp.Segment) (App_registeredServices_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_registeredServices_Results{st}, err
}

func ReadRootApp_registeredServices_Results(msg *capnp.Message) (App_registeredServices_Results, error) {
	root, err := msg.RootPtr()
	return App_registeredServices_Results{root.Struct()}, err
}

func (s App_registeredServices_Results) String() string {
	str, _ := text.Marshal(0xae6825c3fecb35bf, s.Struct)
	return str
}

func (s App_registeredServices_Results) ServiceIds() (capnp.UInt64List, error) {
	p, err := s.Struct.Ptr(0)
	return capnp.UInt64List{List: p.List()}, err
}

func (s App_registeredServices_Results) HasServiceIds() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s App_registeredServices_Results) SetServiceIds(v capnp.UInt64List) error {
	return s.Struct.SetPtr(0, v.List.ToPtr())
}

// NewServiceIds sets the serviceIds field to a newly
// allocated capnp.UInt64List, preferring placement in s's segment.
func (s App_registeredServices_Results) NewServiceIds(n int32) (capnp.UInt64List, error) {
	l, err := capnp.NewUInt64List(s.Struct.Segment(), n)
	if err != nil {
		return capnp.UInt64List{}, err
	}
	err = s.Struct.SetPtr(0, l.List.ToPtr())
	return l, err
}

// App_registeredServices_Results_List is a list of App_registeredServices_Results.
type App_registeredServices_Results_List struct{ capnp.List }

// NewApp_registeredServices_Results creates a new list of App_registeredServices_Results.
func NewApp_registeredServices_Results_List(s *capnp.Segment, sz int32) (App_registeredServices_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return App_registeredServices_Results_List{l}, err
}

func (s App_registeredServices_Results_List) At(i int) App_registeredServices_Results {
	return App_registeredServices_Results{s.List.Struct(i)}
}

func (s App_registeredServices_Results_List) Set(i int, v App_registeredServices_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_registeredServices_Results_List) String() string {
	str, _ := text.MarshalList(0xae6825c3fecb35bf, s.List)
	return str
}

// App_registeredServices_Results_Promise is a wrapper for a App_registeredServices_Results promised by a client call.
type App_registeredServices_Results_Promise struct{ *capnp.Pipeline }

func (p App_registeredServices_Results_Promise) Struct() (App_registeredServices_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_registeredServices_Results{s}, err
}

type App_service_Params struct{ capnp.Struct }

// App_service_Params_TypeID is the unique identifier for the type App_service_Params.
const App_service_Params_TypeID = 0xb95426b082b00c25

func NewApp_service_Params(s *capnp.Segment) (App_service_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_service_Params{st}, err
}

func NewRootApp_service_Params(s *capnp.Segment) (App_service_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return App_service_Params{st}, err
}

func ReadRootApp_service_Params(msg *capnp.Message) (App_service_Params, error) {
	root, err := msg.RootPtr()
	return App_service_Params{root.Struct()}, err
}

func (s App_service_Params) String() string {
	str, _ := text.Marshal(0xb95426b082b00c25, s.Struct)
	return str
}

func (s App_service_Params) Id() uint64 {
	return s.Struct.Uint64(0)
}

func (s App_service_Params) SetId(v uint64) {
	s.Struct.SetUint64(0, v)
}

// App_service_Params_List is a list of App_service_Params.
type App_service_Params_List struct{ capnp.List }

// NewApp_service_Params creates a new list of App_service_Params.
func NewApp_service_Params_List(s *capnp.Segment, sz int32) (App_service_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return App_service_Params_List{l}, err
}

func (s App_service_Params_List) At(i int) App_service_Params {
	return App_service_Params{s.List.Struct(i)}
}

func (s App_service_Params_List) Set(i int, v App_service_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_service_Params_List) String() string {
	str, _ := text.MarshalList(0xb95426b082b00c25, s.List)
	return str
}

// App_service_Params_Promise is a wrapper for a App_service_Params promised by a client call.
type App_service_Params_Promise struct{ *capnp.Pipeline }

func (p App_service_Params_Promise) Struct() (App_service_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_service_Params{s}, err
}

type App_service_Results struct{ capnp.Struct }

// App_service_Results_TypeID is the unique identifier for the type App_service_Results.
const App_service_Results_TypeID = 0xeb68797cd74f95c2

func NewApp_service_Results(s *capnp.Segment) (App_service_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_service_Results{st}, err
}

func NewRootApp_service_Results(s *capnp.Segment) (App_service_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return App_service_Results{st}, err
}

func ReadRootApp_service_Results(msg *capnp.Message) (App_service_Results, error) {
	root, err := msg.RootPtr()
	return App_service_Results{root.Struct()}, err
}

func (s App_service_Results) String() string {
	str, _ := text.Marshal(0xeb68797cd74f95c2, s.Struct)
	return str
}

func (s App_service_Results) Service() Service {
	p, _ := s.Struct.Ptr(0)
	return Service{Client: p.Interface().Client()}
}

func (s App_service_Results) HasService() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s App_service_Results) SetService(v Service) error {
	if v.Client == nil {
		return s.Struct.SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(v.Client))
	return s.Struct.SetPtr(0, in.ToPtr())
}

// App_service_Results_List is a list of App_service_Results.
type App_service_Results_List struct{ capnp.List }

// NewApp_service_Results creates a new list of App_service_Results.
func NewApp_service_Results_List(s *capnp.Segment, sz int32) (App_service_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return App_service_Results_List{l}, err
}

func (s App_service_Results_List) At(i int) App_service_Results {
	return App_service_Results{s.List.Struct(i)}
}

func (s App_service_Results_List) Set(i int, v App_service_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_service_Results_List) String() string {
	str, _ := text.MarshalList(0xeb68797cd74f95c2, s.List)
	return str
}

// App_service_Results_Promise is a wrapper for a App_service_Results promised by a client call.
type App_service_Results_Promise struct{ *capnp.Pipeline }

func (p App_service_Results_Promise) Struct() (App_service_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_service_Results{s}, err
}

func (p App_service_Results_Promise) Service() Service {
	return Service{Client: p.Pipeline.GetPipeline(0).Client()}
}

type App_kill_Params struct{ capnp.Struct }

// App_kill_Params_TypeID is the unique identifier for the type App_kill_Params.
const App_kill_Params_TypeID = 0xa504000ac6204c12

func NewApp_kill_Params(s *capnp.Segment) (App_kill_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_kill_Params{st}, err
}

func NewRootApp_kill_Params(s *capnp.Segment) (App_kill_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_kill_Params{st}, err
}

func ReadRootApp_kill_Params(msg *capnp.Message) (App_kill_Params, error) {
	root, err := msg.RootPtr()
	return App_kill_Params{root.Struct()}, err
}

func (s App_kill_Params) String() string {
	str, _ := text.Marshal(0xa504000ac6204c12, s.Struct)
	return str
}

// App_kill_Params_List is a list of App_kill_Params.
type App_kill_Params_List struct{ capnp.List }

// NewApp_kill_Params creates a new list of App_kill_Params.
func NewApp_kill_Params_List(s *capnp.Segment, sz int32) (App_kill_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_kill_Params_List{l}, err
}

func (s App_kill_Params_List) At(i int) App_kill_Params { return App_kill_Params{s.List.Struct(i)} }

func (s App_kill_Params_List) Set(i int, v App_kill_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_kill_Params_List) String() string {
	str, _ := text.MarshalList(0xa504000ac6204c12, s.List)
	return str
}

// App_kill_Params_Promise is a wrapper for a App_kill_Params promised by a client call.
type App_kill_Params_Promise struct{ *capnp.Pipeline }

func (p App_kill_Params_Promise) Struct() (App_kill_Params, error) {
	s, err := p.Pipeline.Struct()
	return App_kill_Params{s}, err
}

type App_kill_Results struct{ capnp.Struct }

// App_kill_Results_TypeID is the unique identifier for the type App_kill_Results.
const App_kill_Results_TypeID = 0xfa41cf108b6d790d

func NewApp_kill_Results(s *capnp.Segment) (App_kill_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_kill_Results{st}, err
}

func NewRootApp_kill_Results(s *capnp.Segment) (App_kill_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return App_kill_Results{st}, err
}

func ReadRootApp_kill_Results(msg *capnp.Message) (App_kill_Results, error) {
	root, err := msg.RootPtr()
	return App_kill_Results{root.Struct()}, err
}

func (s App_kill_Results) String() string {
	str, _ := text.Marshal(0xfa41cf108b6d790d, s.Struct)
	return str
}

// App_kill_Results_List is a list of App_kill_Results.
type App_kill_Results_List struct{ capnp.List }

// NewApp_kill_Results creates a new list of App_kill_Results.
func NewApp_kill_Results_List(s *capnp.Segment, sz int32) (App_kill_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return App_kill_Results_List{l}, err
}

func (s App_kill_Results_List) At(i int) App_kill_Results { return App_kill_Results{s.List.Struct(i)} }

func (s App_kill_Results_List) Set(i int, v App_kill_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s App_kill_Results_List) String() string {
	str, _ := text.MarshalList(0xfa41cf108b6d790d, s.List)
	return str
}

// App_kill_Results_Promise is a wrapper for a App_kill_Results promised by a client call.
type App_kill_Results_Promise struct{ *capnp.Pipeline }

func (p App_kill_Results_Promise) Struct() (App_kill_Results, error) {
	s, err := p.Pipeline.Struct()
	return App_kill_Results{s}, err
}

type LogLevel uint16

// LogLevel_TypeID is the unique identifier for the type LogLevel.
const LogLevel_TypeID = 0xce802aa8977a9aee

// Values of LogLevel.
const (
	LogLevel_debug LogLevel = 0
	LogLevel_info  LogLevel = 1
	LogLevel_warn  LogLevel = 2
	LogLevel_error LogLevel = 3
)

// String returns the enum's constant name.
func (c LogLevel) String() string {
	switch c {
	case LogLevel_debug:
		return "debug"
	case LogLevel_info:
		return "info"
	case LogLevel_warn:
		return "warn"
	case LogLevel_error:
		return "error"

	default:
		return ""
	}
}

// LogLevelFromString returns the enum value with a name,
// or the zero value if there's no such value.
func LogLevelFromString(c string) LogLevel {
	switch c {
	case "debug":
		return LogLevel_debug
	case "info":
		return LogLevel_info
	case "warn":
		return LogLevel_warn
	case "error":
		return LogLevel_error

	default:
		return 0
	}
}

type LogLevel_List struct{ capnp.List }

func NewLogLevel_List(s *capnp.Segment, sz int32) (LogLevel_List, error) {
	l, err := capnp.NewUInt16List(s, sz)
	return LogLevel_List{l.List}, err
}

func (l LogLevel_List) At(i int) LogLevel {
	ul := capnp.UInt16List{List: l.List}
	return LogLevel(ul.At(i))
}

func (l LogLevel_List) Set(i int, v LogLevel) {
	ul := capnp.UInt16List{List: l.List}
	ul.Set(i, uint16(v))
}

type Service struct{ Client capnp.Client }

// Service_TypeID is the unique identifier for the type Service.
const Service_TypeID = 0xb25b411cec149334

func (c Service) Id(ctx context.Context, params func(Service_id_Params) error, opts ...capnp.CallOption) Service_id_Results_Promise {
	if c.Client == nil {
		return Service_id_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      0,
			InterfaceName: "app.capnp:Service",
			MethodName:    "id",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(Service_id_Params{Struct: s}) }
	}
	return Service_id_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c Service) LogLevel(ctx context.Context, params func(Service_logLevel_Params) error, opts ...capnp.CallOption) Service_logLevel_Results_Promise {
	if c.Client == nil {
		return Service_logLevel_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      1,
			InterfaceName: "app.capnp:Service",
			MethodName:    "logLevel",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(Service_logLevel_Params{Struct: s}) }
	}
	return Service_logLevel_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c Service) Alive(ctx context.Context, params func(Service_alive_Params) error, opts ...capnp.CallOption) Service_alive_Results_Promise {
	if c.Client == nil {
		return Service_alive_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      2,
			InterfaceName: "app.capnp:Service",
			MethodName:    "alive",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(Service_alive_Params{Struct: s}) }
	}
	return Service_alive_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c Service) Kill(ctx context.Context, params func(Service_kill_Params) error, opts ...capnp.CallOption) Service_kill_Results_Promise {
	if c.Client == nil {
		return Service_kill_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      3,
			InterfaceName: "app.capnp:Service",
			MethodName:    "kill",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(Service_kill_Params{Struct: s}) }
	}
	return Service_kill_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}

type Service_Server interface {
	Id(Service_id) error

	LogLevel(Service_logLevel) error

	Alive(Service_alive) error

	Kill(Service_kill) error
}

func Service_ServerToClient(s Service_Server) Service {
	c, _ := s.(server.Closer)
	return Service{Client: server.New(Service_Methods(nil, s), c)}
}

func Service_Methods(methods []server.Method, s Service_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      0,
			InterfaceName: "app.capnp:Service",
			MethodName:    "id",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := Service_id{c, opts, Service_id_Params{Struct: p}, Service_id_Results{Struct: r}}
			return s.Id(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      1,
			InterfaceName: "app.capnp:Service",
			MethodName:    "logLevel",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := Service_logLevel{c, opts, Service_logLevel_Params{Struct: p}, Service_logLevel_Results{Struct: r}}
			return s.LogLevel(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      2,
			InterfaceName: "app.capnp:Service",
			MethodName:    "alive",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := Service_alive{c, opts, Service_alive_Params{Struct: p}, Service_alive_Results{Struct: r}}
			return s.Alive(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb25b411cec149334,
			MethodID:      3,
			InterfaceName: "app.capnp:Service",
			MethodName:    "kill",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := Service_kill{c, opts, Service_kill_Params{Struct: p}, Service_kill_Results{Struct: r}}
			return s.Kill(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 0},
	})

	return methods
}

// Service_id holds the arguments for a server call to Service.id.
type Service_id struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  Service_id_Params
	Results Service_id_Results
}

// Service_logLevel holds the arguments for a server call to Service.logLevel.
type Service_logLevel struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  Service_logLevel_Params
	Results Service_logLevel_Results
}

// Service_alive holds the arguments for a server call to Service.alive.
type Service_alive struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  Service_alive_Params
	Results Service_alive_Results
}

// Service_kill holds the arguments for a server call to Service.kill.
type Service_kill struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  Service_kill_Params
	Results Service_kill_Results
}

type Service_id_Params struct{ capnp.Struct }

// Service_id_Params_TypeID is the unique identifier for the type Service_id_Params.
const Service_id_Params_TypeID = 0x965465bd75220f94

func NewService_id_Params(s *capnp.Segment) (Service_id_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_id_Params{st}, err
}

func NewRootService_id_Params(s *capnp.Segment) (Service_id_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_id_Params{st}, err
}

func ReadRootService_id_Params(msg *capnp.Message) (Service_id_Params, error) {
	root, err := msg.RootPtr()
	return Service_id_Params{root.Struct()}, err
}

func (s Service_id_Params) String() string {
	str, _ := text.Marshal(0x965465bd75220f94, s.Struct)
	return str
}

// Service_id_Params_List is a list of Service_id_Params.
type Service_id_Params_List struct{ capnp.List }

// NewService_id_Params creates a new list of Service_id_Params.
func NewService_id_Params_List(s *capnp.Segment, sz int32) (Service_id_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Service_id_Params_List{l}, err
}

func (s Service_id_Params_List) At(i int) Service_id_Params {
	return Service_id_Params{s.List.Struct(i)}
}

func (s Service_id_Params_List) Set(i int, v Service_id_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_id_Params_List) String() string {
	str, _ := text.MarshalList(0x965465bd75220f94, s.List)
	return str
}

// Service_id_Params_Promise is a wrapper for a Service_id_Params promised by a client call.
type Service_id_Params_Promise struct{ *capnp.Pipeline }

func (p Service_id_Params_Promise) Struct() (Service_id_Params, error) {
	s, err := p.Pipeline.Struct()
	return Service_id_Params{s}, err
}

type Service_id_Results struct{ capnp.Struct }

// Service_id_Results_TypeID is the unique identifier for the type Service_id_Results.
const Service_id_Results_TypeID = 0xccdde1728f71e904

func NewService_id_Results(s *capnp.Segment) (Service_id_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_id_Results{st}, err
}

func NewRootService_id_Results(s *capnp.Segment) (Service_id_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_id_Results{st}, err
}

func ReadRootService_id_Results(msg *capnp.Message) (Service_id_Results, error) {
	root, err := msg.RootPtr()
	return Service_id_Results{root.Struct()}, err
}

func (s Service_id_Results) String() string {
	str, _ := text.Marshal(0xccdde1728f71e904, s.Struct)
	return str
}

func (s Service_id_Results) ServiceId() uint64 {
	return s.Struct.Uint64(0)
}

func (s Service_id_Results) SetServiceId(v uint64) {
	s.Struct.SetUint64(0, v)
}

// Service_id_Results_List is a list of Service_id_Results.
type Service_id_Results_List struct{ capnp.List }

// NewService_id_Results creates a new list of Service_id_Results.
func NewService_id_Results_List(s *capnp.Segment, sz int32) (Service_id_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return Service_id_Results_List{l}, err
}

func (s Service_id_Results_List) At(i int) Service_id_Results {
	return Service_id_Results{s.List.Struct(i)}
}

func (s Service_id_Results_List) Set(i int, v Service_id_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_id_Results_List) String() string {
	str, _ := text.MarshalList(0xccdde1728f71e904, s.List)
	return str
}

// Service_id_Results_Promise is a wrapper for a Service_id_Results promised by a client call.
type Service_id_Results_Promise struct{ *capnp.Pipeline }

func (p Service_id_Results_Promise) Struct() (Service_id_Results, error) {
	s, err := p.Pipeline.Struct()
	return Service_id_Results{s}, err
}

type Service_logLevel_Params struct{ capnp.Struct }

// Service_logLevel_Params_TypeID is the unique identifier for the type Service_logLevel_Params.
const Service_logLevel_Params_TypeID = 0xa6b9c11c2aac9785

func NewService_logLevel_Params(s *capnp.Segment) (Service_logLevel_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_logLevel_Params{st}, err
}

func NewRootService_logLevel_Params(s *capnp.Segment) (Service_logLevel_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_logLevel_Params{st}, err
}

func ReadRootService_logLevel_Params(msg *capnp.Message) (Service_logLevel_Params, error) {
	root, err := msg.RootPtr()
	return Service_logLevel_Params{root.Struct()}, err
}

func (s Service_logLevel_Params) String() string {
	str, _ := text.Marshal(0xa6b9c11c2aac9785, s.Struct)
	return str
}

// Service_logLevel_Params_List is a list of Service_logLevel_Params.
type Service_logLevel_Params_List struct{ capnp.List }

// NewService_logLevel_Params creates a new list of Service_logLevel_Params.
func NewService_logLevel_Params_List(s *capnp.Segment, sz int32) (Service_logLevel_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Service_logLevel_Params_List{l}, err
}

func (s Service_logLevel_Params_List) At(i int) Service_logLevel_Params {
	return Service_logLevel_Params{s.List.Struct(i)}
}

func (s Service_logLevel_Params_List) Set(i int, v Service_logLevel_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_logLevel_Params_List) String() string {
	str, _ := text.MarshalList(0xa6b9c11c2aac9785, s.List)
	return str
}

// Service_logLevel_Params_Promise is a wrapper for a Service_logLevel_Params promised by a client call.
type Service_logLevel_Params_Promise struct{ *capnp.Pipeline }

func (p Service_logLevel_Params_Promise) Struct() (Service_logLevel_Params, error) {
	s, err := p.Pipeline.Struct()
	return Service_logLevel_Params{s}, err
}

type Service_logLevel_Results struct{ capnp.Struct }

// Service_logLevel_Results_TypeID is the unique identifier for the type Service_logLevel_Results.
const Service_logLevel_Results_TypeID = 0x9285c4944dfb709f

func NewService_logLevel_Results(s *capnp.Segment) (Service_logLevel_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_logLevel_Results{st}, err
}

func NewRootService_logLevel_Results(s *capnp.Segment) (Service_logLevel_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_logLevel_Results{st}, err
}

func ReadRootService_logLevel_Results(msg *capnp.Message) (Service_logLevel_Results, error) {
	root, err := msg.RootPtr()
	return Service_logLevel_Results{root.Struct()}, err
}

func (s Service_logLevel_Results) String() string {
	str, _ := text.Marshal(0x9285c4944dfb709f, s.Struct)
	return str
}

func (s Service_logLevel_Results) Level() LogLevel {
	return LogLevel(s.Struct.Uint16(0))
}

func (s Service_logLevel_Results) SetLevel(v LogLevel) {
	s.Struct.SetUint16(0, uint16(v))
}

// Service_logLevel_Results_List is a list of Service_logLevel_Results.
type Service_logLevel_Results_List struct{ capnp.List }

// NewService_logLevel_Results creates a new list of Service_logLevel_Results.
func NewService_logLevel_Results_List(s *capnp.Segment, sz int32) (Service_logLevel_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return Service_logLevel_Results_List{l}, err
}

func (s Service_logLevel_Results_List) At(i int) Service_logLevel_Results {
	return Service_logLevel_Results{s.List.Struct(i)}
}

func (s Service_logLevel_Results_List) Set(i int, v Service_logLevel_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_logLevel_Results_List) String() string {
	str, _ := text.MarshalList(0x9285c4944dfb709f, s.List)
	return str
}

// Service_logLevel_Results_Promise is a wrapper for a Service_logLevel_Results promised by a client call.
type Service_logLevel_Results_Promise struct{ *capnp.Pipeline }

func (p Service_logLevel_Results_Promise) Struct() (Service_logLevel_Results, error) {
	s, err := p.Pipeline.Struct()
	return Service_logLevel_Results{s}, err
}

type Service_alive_Params struct{ capnp.Struct }

// Service_alive_Params_TypeID is the unique identifier for the type Service_alive_Params.
const Service_alive_Params_TypeID = 0x91dfcb778d8d16c0

func NewService_alive_Params(s *capnp.Segment) (Service_alive_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_alive_Params{st}, err
}

func NewRootService_alive_Params(s *capnp.Segment) (Service_alive_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_alive_Params{st}, err
}

func ReadRootService_alive_Params(msg *capnp.Message) (Service_alive_Params, error) {
	root, err := msg.RootPtr()
	return Service_alive_Params{root.Struct()}, err
}

func (s Service_alive_Params) String() string {
	str, _ := text.Marshal(0x91dfcb778d8d16c0, s.Struct)
	return str
}

// Service_alive_Params_List is a list of Service_alive_Params.
type Service_alive_Params_List struct{ capnp.List }

// NewService_alive_Params creates a new list of Service_alive_Params.
func NewService_alive_Params_List(s *capnp.Segment, sz int32) (Service_alive_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Service_alive_Params_List{l}, err
}

func (s Service_alive_Params_List) At(i int) Service_alive_Params {
	return Service_alive_Params{s.List.Struct(i)}
}

func (s Service_alive_Params_List) Set(i int, v Service_alive_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_alive_Params_List) String() string {
	str, _ := text.MarshalList(0x91dfcb778d8d16c0, s.List)
	return str
}

// Service_alive_Params_Promise is a wrapper for a Service_alive_Params promised by a client call.
type Service_alive_Params_Promise struct{ *capnp.Pipeline }

func (p Service_alive_Params_Promise) Struct() (Service_alive_Params, error) {
	s, err := p.Pipeline.Struct()
	return Service_alive_Params{s}, err
}

type Service_alive_Results struct{ capnp.Struct }

// Service_alive_Results_TypeID is the unique identifier for the type Service_alive_Results.
const Service_alive_Results_TypeID = 0xe542d95b68592c1c

func NewService_alive_Results(s *capnp.Segment) (Service_alive_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_alive_Results{st}, err
}

func NewRootService_alive_Results(s *capnp.Segment) (Service_alive_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Service_alive_Results{st}, err
}

func ReadRootService_alive_Results(msg *capnp.Message) (Service_alive_Results, error) {
	root, err := msg.RootPtr()
	return Service_alive_Results{root.Struct()}, err
}

func (s Service_alive_Results) String() string {
	str, _ := text.Marshal(0xe542d95b68592c1c, s.Struct)
	return str
}

func (s Service_alive_Results) Alive() bool {
	return s.Struct.Bit(0)
}

func (s Service_alive_Results) SetAlive(v bool) {
	s.Struct.SetBit(0, v)
}

// Service_alive_Results_List is a list of Service_alive_Results.
type Service_alive_Results_List struct{ capnp.List }

// NewService_alive_Results creates a new list of Service_alive_Results.
func NewService_alive_Results_List(s *capnp.Segment, sz int32) (Service_alive_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return Service_alive_Results_List{l}, err
}

func (s Service_alive_Results_List) At(i int) Service_alive_Results {
	return Service_alive_Results{s.List.Struct(i)}
}

func (s Service_alive_Results_List) Set(i int, v Service_alive_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_alive_Results_List) String() string {
	str, _ := text.MarshalList(0xe542d95b68592c1c, s.List)
	return str
}

// Service_alive_Results_Promise is a wrapper for a Service_alive_Results promised by a client call.
type Service_alive_Results_Promise struct{ *capnp.Pipeline }

func (p Service_alive_Results_Promise) Struct() (Service_alive_Results, error) {
	s, err := p.Pipeline.Struct()
	return Service_alive_Results{s}, err
}

type Service_kill_Params struct{ capnp.Struct }

// Service_kill_Params_TypeID is the unique identifier for the type Service_kill_Params.
const Service_kill_Params_TypeID = 0xe3ec490c3d4015bb

func NewService_kill_Params(s *capnp.Segment) (Service_kill_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_kill_Params{st}, err
}

func NewRootService_kill_Params(s *capnp.Segment) (Service_kill_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_kill_Params{st}, err
}

func ReadRootService_kill_Params(msg *capnp.Message) (Service_kill_Params, error) {
	root, err := msg.RootPtr()
	return Service_kill_Params{root.Struct()}, err
}

func (s Service_kill_Params) String() string {
	str, _ := text.Marshal(0xe3ec490c3d4015bb, s.Struct)
	return str
}

// Service_kill_Params_List is a list of Service_kill_Params.
type Service_kill_Params_List struct{ capnp.List }

// NewService_kill_Params creates a new list of Service_kill_Params.
func NewService_kill_Params_List(s *capnp.Segment, sz int32) (Service_kill_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Service_kill_Params_List{l}, err
}

func (s Service_kill_Params_List) At(i int) Service_kill_Params {
	return Service_kill_Params{s.List.Struct(i)}
}

func (s Service_kill_Params_List) Set(i int, v Service_kill_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_kill_Params_List) String() string {
	str, _ := text.MarshalList(0xe3ec490c3d4015bb, s.List)
	return str
}

// Service_kill_Params_Promise is a wrapper for a Service_kill_Params promised by a client call.
type Service_kill_Params_Promise struct{ *capnp.Pipeline }

func (p Service_kill_Params_Promise) Struct() (Service_kill_Params, error) {
	s, err := p.Pipeline.Struct()
	return Service_kill_Params{s}, err
}

type Service_kill_Results struct{ capnp.Struct }

// Service_kill_Results_TypeID is the unique identifier for the type Service_kill_Results.
const Service_kill_Results_TypeID = 0xf95512d6a5f5e530

func NewService_kill_Results(s *capnp.Segment) (Service_kill_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_kill_Results{st}, err
}

func NewRootService_kill_Results(s *capnp.Segment) (Service_kill_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_kill_Results{st}, err
}

func ReadRootService_kill_Results(msg *capnp.Message) (Service_kill_Results, error) {
	root, err := msg.RootPtr()
	return Service_kill_Results{root.Struct()}, err
}

func (s Service_kill_Results) String() string {
	str, _ := text.Marshal(0xf95512d6a5f5e530, s.Struct)
	return str
}

// Service_kill_Results_List is a list of Service_kill_Results.
type Service_kill_Results_List struct{ capnp.List }

// NewService_kill_Results creates a new list of Service_kill_Results.
func NewService_kill_Results_List(s *capnp.Segment, sz int32) (Service_kill_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Service_kill_Results_List{l}, err
}

func (s Service_kill_Results_List) At(i int) Service_kill_Results {
	return Service_kill_Results{s.List.Struct(i)}
}

func (s Service_kill_Results_List) Set(i int, v Service_kill_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s Service_kill_Results_List) String() string {
	str, _ := text.MarshalList(0xf95512d6a5f5e530, s.List)
	return str
}

// Service_kill_Results_Promise is a wrapper for a Service_kill_Results promised by a client call.
type Service_kill_Results_Promise struct{ *capnp.Pipeline }

func (p Service_kill_Results_Promise) Struct() (Service_kill_Results, error) {
	s, err := p.Pipeline.Struct()
	return Service_kill_Results{s}, err
}

const schema_db8274f9144abc7e = "x\xda\xa4VolSU\x14?\xe7\xbe\xfb\xfa\x1c\x19" +
	"\x94\xdb7\x8c\xc2\xb0\xce\x0c\x03\x8b\xcc\xfd\xd1\x0f\x92\x98" +
	"uKL\xec2B[Gt\x10?<\xd7\xe7\xd6\xd8" +
	"u\xdd{\xdd\xc8\xd0\xf9\x87\x8c\x0f\xc4,\x0b\x13\\X" +
	"b\xfcB\x89$\xce\x80f&\x8bL\x05\x1dFq\x98" +
	"\x91(\"\x10D]\x0c\xba\x18\x871\xba\x19|\xe6\xbe" +
	"\xee\xb6wk\xc7\x17?\xb5\xc9\xf9s\x7f\xe7w~\xe7" +
	"\x9cWu\x99\x04H\xb5\xea\x14\x01\x84S\xaa\xe7V\xd7" +
	"\x93\xe9\x0dc?\xf5\xb35\x08@5\x00}\x86.\x00" +
	"u.\xcez\xa6J\x9e\x9a\x1b\x84\x9c\xe1sz\x13\xa8" +
	"3\xbbzbR\xed\xff{\x10\xc2kPXF\xe9\x02" +
	"\xa0~\x92\xd6\x01:\x1f\xdf90\xb0\xe7\xdc\xb5\x83\xc0" +
	"|\xc2<\xedf|3\xf9\xcf\xf6C\x9f\xee\x1f\x82\xb0" +
	"O\x04\xd6\x8e\xd1\xf5\x08\xa8O\xb8\x91\xf6\xfb\xf5\x03\xf1" +
	"?\x8e\x0ee\x9eT\x91\x87^u3_w\xed\x87\xbc" +
	"\xf7uO\x98\xcd\xafK\x99U\xf5\x07\xa0\xd7|M\xf7" +
	"\x9e]E\xd39\xa47\xe8\x05\xa0\xce\xb7W\x9a\xae\x1c" +
	"\x9d\xebLK%L\xd13@\x9d\xfd\xc3oW\x94\x9e" +
	"\x1e?\x96KT;J}\x08\xf4\xafX\xd2y\xfc\x1e" +
	"\xdf\xf1l@\xeda\xda\x80@\x9d\x8f\x1e>\xf7\xef'" +
	"\x9b\xda\xdf\x91\xa0\xd5\xf6\xd1F\x8e\xfd\x80\x8b\xed\xa1\xd7" +
	"JfK\xebw\xbf\x0bl\x95\xe2\xbcx\xaa\xb1d>" +
	"\xb5\xef2\xb8\xa5\x0d\xe9\x93n\xaa\xd3TC\xddT5" +
	"\x00\xe7\xe9\xad\x0f\xee\x1a\xde\xa0\x8cI\x1c\xd6nW\x09" +
	"O\x17Vy\xbaM\xc5'\xf6\x9d\xb8\xbfy\\&\xb9" +
	"[\xfd\x05P\xefu\xed\xbd\xa7\xf66V\x9f?\xf6\xa1" +
	"T\xda\x11\x95w\x87\xde\xe8\x1a\xb4\xae_\xfdR\"Y" +
	"\xefs\x03_q\x03\x7f\x1b\xd9;\xfcV\xc5\xcb\xe7\x81" +
	"\xad\"Kp\xa6\xd5\x11}\x94\x83\xd3\x8f\xabm\x80\xce" +
	"\xd9\xe7\x9b\x176oi\xb9 #\x98R\xbf\x00\xd4\xa7" +
	"\xddD\x1f\xac\x0b<Z\x1c\x9c\xfdQj\xc6\x9c\x8b\xa0" +
	"\xf4\x81\x96\xf6\xdd\x97\x1af\xe46\x7f\x9d\xa9\xed\x92\x1b" +
	"y\xe6\xf0\x8e\x8b/\xf4\xb6\xff*\xb7y^\xbd\x09\xa8" +
	"\xdfr\xedG\xd8{\xfd\xdf\xff\x1c\xf9=\x8f\xca\x8d\x1e" +
	"K/\xf3\xf0|\x1b=\x9f\xa1\x1e\xd48\x95U3\x7f" +
	"\xa6\xbf\xf1\xed\x9c\x97pTk\\n\xab{;^]" +
	"\xfbU\xfd\x82D\xd1:\xed;\xa8r\x8cd\xb2\xb2\xd5" +
	"H&Hr[}2Yi\xa7\x0c+eFw$" +
	"\xca\xebB\x86et\xd8\xcb\x1d\xe2\x9dmMf\x8f\x19" +
	"/\x0f\xf9oo\x8f\xd4\x99vw<e\x87\xa9B\x01" +
	"(\x02\xb0\xd55\x00\xe1;\x14\x0c\x97\x10\xf4\xc7\xb9\x17" +
	"zs=\x00D/\xa0\x9c\xef\x09\xd3\xea\x89\xb5\x9a\x95" +
	"F<\xd6c\xe6\x01Rr\x0e\xb9G\xf9\x9b\xca\xffz" +
	"\x94\x17\x11K\xd8)#\xd1j\x16,b\x17@\xb8X" +
	"\xc1\xf0]\x04\x1d\xe1\x08J0\x8a\xc5@\xb0\xb8p\x05" +
	"\xb1hy\xc8\xb0\xb4\x02|=\x17\x8b\xc7\xcb\xdd\xca0" +
	"g\xf3,\xc2\x88f,6\x08C\x81\x92\x97\xc7\x16e" +
	"b-\xb3-f\xa7L\xcb\x8c.F\xd8\xf9\xb9V\xf0" +
	"\x8bdj\x06(T\xf5f\x82\x8e\x9d\xf1\x0c\x82\x12\xb5" +
	"q\x0d`HA,\x02\xc2\xfffa\xa0\x80\x8af\x08" +
	"1\xbcVQ\x01\xb2;\x0b\xc5`\xb2\xae\xf5@\x98\xa9" +
	"!f\xd7\x10\x8a\xcd\xc8Z\x1a\x81\xb0\xb0\x86$\xbbE" +
	"Q\x8c\x13{\xac\x06\x08{DC%;z(\xb4\xcf" +
	"\xb6V\x00ae\x9a\x12\x8b\x06\xd0\x11<\x01@\x00\xfd" +
	"\xae\x92\x02\xe8\xe5\xac\x070\x84(\xabi\xa9\xfe\x05\x0b" +
	"2\x09\x11\xa9\xf5\xc2\x130\x81*\x10T\xf3e\xb4\xc8" +
	"Sy\xc8\xf0r\xe6\xe5L\xebs\xa2TbQ\x97\xbd" +
	"\xa2\xdb\xe8\xb0\xc0\xb0I\xd2\x8a\x98\xb6w\xb9J\x97@" +
	"\x15\xfd\xc2\xfc\x970\xb9\xad\xc9\xa5H1\xe3n\xa3\x90" +
	"\x00\xb0-5|2XY\x05\x00\x12v7\xffQ\x18" +
	"\xab\x01\xf0G\xcdg\xba\xdb\xbc\xb1\xc4\xb3\x9d\xde=\x86" +
	"\x95\xf0\x9b\x96\xd5i\xe5\xe1\x8e\x16\x16\x91<\x8aF2" +
	"\x19,X\xb8(,3\x19\xfe\x15\x87>\xb3\x15\x0a\xb5" +
	"i\xc93\xdc\x0b\x11\x08\xe2\xca\x0d\x8a\x98\xfe\xbc1o" +
	"\xc8%yi\xd1\x0fY\xee\xb2qz\xa4\x84\xe0w3" +
	"r\x06K]\xa9\x8bs\x8b\xe2t\xb0i.\xf5I." +
	"uq\xafP\xdcx6\xce\xa5~RC\">@r" +
	"G\x91\xa5#@\xd8\x1b\\\xea\xe2+\x04\xc5W\x07;" +
	"\xc8\xe3\x0eh\x98\xbd\xd5\xd2m\xee\x1b\x01\xc2z5T" +
	"\xb3\xf7\x13\xc5\xb1a\x1d\x0d@\x98\xa1\xa1G|-H" +
	"\x07b'\x1f\x9f\xe0\xe2\xf8d\x17\x1c\x1f\x1fY\xf3\xcb" +
	"G\xcb\x11\x8b\x04\xc5&QL;\x90\xa5\xae\xe0\xcc-" +
	"o\xb6\xd8\xb6\x05w\xa4X\xed\xff\x05\x00\x00\xff\xffg" +
	"\x84\xd8\x8c"

func init() {
	schemas.Register(schema_db8274f9144abc7e,
		0x84e4b51ba5570071,
		0x8ff15814cd06ecd7,
		0x8ff88405c5bd0dec,
		0x91dfcb778d8d16c0,
		0x9285c4944dfb709f,
		0x92a4f36c8d41b673,
		0x965465bd75220f94,
		0xa504000ac6204c12,
		0xa56ff1a4dc4cdcd8,
		0xa6b9c11c2aac9785,
		0xa9121e4800ff7069,
		0xae6825c3fecb35bf,
		0xb25b411cec149334,
		0xb5031b975a2f2d5d,
		0xb95426b082b00c25,
		0xbea6ce314a7abc79,
		0xccdde1728f71e904,
		0xce802aa8977a9aee,
		0xd2592928fa547bc6,
		0xe3ec490c3d4015bb,
		0xe542d95b68592c1c,
		0xeb68797cd74f95c2,
		0xf052e7e084b31199,
		0xf95512d6a5f5e530,
		0xfa41cf108b6d790d)
}
